import streamlit as st
from pandas_datareader import data as web
import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
from pypfopt.efficient_frontier import EfficientFrontier
from pypfopt import risk_models
from pypfopt import expected_returns
from pypfopt import objective_functions

st.header('Portfolio Optimization Tool')
st.subheader("This tool is designed to help you determine the optimum distribution of your portfolio based on how much money you have to invest, the risk, and the potential return.  It is designed to optimize on the max Sharpe Ratio.")
st.write("Note, the app may encourage you to not select a stock at all depending on the risk of the investment and it's expected return. ")
with st.beta_expander("What's a Sharpe Ratio?"):
    st.write(""" The Sharpe ratio was developed by Nobel laureate William F. Sharpe and is used to help investors understand the return of an investment compared to its risk. The ratio is the average return earned in excess of the risk-free rate per unit of volatility or total risk. Volatility is a measure of the price fluctuations of an asset or portfolio.

Subtracting the risk-free rate from the mean return allows an investor to better isolate the profits associated with risk-taking activities. The risk-free rate of return is the return on an investment with zero risk, meaning it's the return investors could expect for taking no risk. The yield for a U.S. Treasury bond, for example, could be used as the risk-free rate.

Generally, the greater the value of the Sharpe ratio, the more attractive the risk-adjusted return """)

# Appends some text to the app.


st.sidebar.title("Select your portfolio (Minimum of 3 Stocks)")
assets = [st.sidebar.multiselect('',[
    'A', 'AA', 'AACG', 'AACQ', 'AACQU', 'AACQW', 'AAIC', 'AAIC.PRB',
    'AAIC.PRC', 'AAL', 'AAMC', 'AAME', 'AAN', 'AAOI', 'AAON', 'AAP', 'AAPL',
    'AAT', 'AAU', 'AAWW', 'AAXN', 'AB', 'ABB', 'ABBV', 'ABC', 'ABCB', 'ABCL',
    'ABCM', 'ABEO', 'ABEV', 'ABG', 'ABIO', 'ABM', 'ABMD', 'ABNB', 'ABR',
    'ABR.PRA', 'ABR.PRB', 'ABR.PRC', 'ABST', 'ABT', 'ABTX', 'ABUS', 'AC',
    'ACA', 'ACAC', 'ACACU', 'ACACW', 'ACAD', 'ACAM', 'ACAMU', 'ACAMW', 'ACB',
    'ACBI', 'ACC', 'ACCD', 'ACCO', 'ACCP', 'ACEL', 'ACER', 'ACET', 'ACEV',
    'ACEVU', 'ACEVW', 'ACGL', 'ACGLO', 'ACGLP', 'ACH', 'ACHC', 'ACHV', 'ACI',
    'ACIA', 'ACIC', 'ACIC.U', 'ACIC.WS', 'ACIU', 'ACIW', 'ACKIU', 'ACLL',
    'ACLS', 'ACM', 'ACMR', 'ACN', 'ACNB', 'ACND', 'ACND.U', 'ACND.WS', 'ACOR',
    'ACP', 'ACRE', 'ACRS', 'ACRX', 'ACST', 'ACTC', 'ACTCU', 'ACTCW', 'ACTG',
    'ACU', 'ACV', 'ACY', 'ADAP', 'ADBE', 'ADC', 'ADCT', 'ADES', 'ADFI', 'ADI',
    'ADIL', 'ADILW', 'ADM', 'ADMA', 'ADME', 'ADMP', 'ADMS', 'ADNT', 'ADOC',
    'ADOCR', 'ADOCW', 'ADP', 'ADPT', 'ADS', 'ADSK', 'ADT', 'ADTN', 'ADTX',
    'ADUS', 'ADV', 'ADVM', 'ADVWW', 'ADX', 'ADXN', 'ADXS', 'AE', 'AEB', 'AEE',
    'AEF', 'AEFC', 'AEG', 'AEGN', 'AEHL', 'AEHR', 'AEIS', 'AEL', 'AEL.PRA',
    'AEL.PRB', 'AEM', 'AEMD', 'AENZ', 'AEO', 'AEP', 'AEPPL', 'AEPPZ', 'AER',
    'AERI', 'AES', 'AESE', 'AESR', 'AEY', 'AEYE', 'AEZS', 'AFB', 'AFC', 'AFG',
    'AFGB', 'AFGC', 'AFGD', 'AFGE', 'AFI', 'AFIB', 'AFIN', 'AFINO', 'AFINP',
    'AFL', 'AFMD', 'AFT', 'AFYA', 'AG', 'AGBA', 'AGBAR', 'AGBAU', 'AGBAW',
    'AGC', 'AGCO', 'AGCUU', 'AGCWW', 'AGD', 'AGE', 'AGEN', 'AGFS', 'AGI',
    'AGIO', 'AGLE', 'AGM', 'AGM.A', 'AGM.PRC', 'AGM.PRD', 'AGM.PRE', 'AGM.PRF',
    'AGMH', 'AGNC', 'AGNCM', 'AGNCN', 'AGNCO', 'AGNCP', 'AGO', 'AGO.PRB',
    'AGO.PRE', 'AGO.PRF', 'AGR', 'AGRO', 'AGRX', 'AGS', 'AGTC', 'AGX', 'AGYS',
    'AHAC', 'AHACU', 'AHACW', 'AHC', 'AHCO', 'AHH', 'AHH.PRA', 'AHI',
    'AHL.PRC', 'AHL.PRD', 'AHL.PRE', 'AHPI', 'AHT', 'AHT.PRD', 'AHT.PRF',
    'AHT.PRG', 'AHT.PRH', 'AHT.PRI', 'AI', 'AIC', 'AIF', 'AIG', 'AIG.PRA',
    'AIG.WS', 'AIH', 'AIHS', 'AIKI', 'AIM', 'AIMC', 'AIN', 'AINC', 'AINV',
    'AIO', 'AIR', 'AIRC', 'AIRG', 'AIRI', 'AIRT', 'AIRTP', 'AIRTW', 'AIT',
    'AIV', 'AIW', 'AIZ', 'AIZN', 'AIZP', 'AJAX', 'AJAX.U', 'AJAX.WS', 'AJG',
    'AJRD', 'AJX', 'AJXA', 'AKAM', 'AKBA', 'AKER', 'AKO/A', 'AKO/B', 'AKR',
    'AKRO', 'AKTS', 'AKTX', 'AKU', 'AKUS', 'AL', 'AL.PRA', 'ALAC', 'ALACR',
    'ALACU', 'ALACW', 'ALB', 'ALBO', 'ALC', 'ALCO', 'ALDX', 'ALE', 'ALEC',
    'ALEX', 'ALG', 'ALGM', 'ALGN', 'ALGS', 'ALGT', 'ALIM', 'ALIN.PRA',
    'ALIN.PRB', 'ALIN.PRE', 'ALIT', 'ALJJ', 'ALK', 'ALKS', 'ALL', 'ALL.PRB',
    'ALL.PRG', 'ALL.PRH', 'ALL.PRI', 'ALLE', 'ALLK', 'ALLO', 'ALLT', 'ALLY',
    'ALLY.PRA', 'ALNA', 'ALNY', 'ALOT', 'ALP.PRQ', 'ALPN', 'ALRM', 'ALRN',
    'ALRS', 'ALSK', 'ALSN', 'ALT', 'ALTA', 'ALTG', 'ALTG.PRA', 'ALTG.WS',
    'ALTM', 'ALTR', 'ALTUU', 'ALUS', 'ALUS.U', 'ALUS.WS', 'ALV', 'ALVR', 'ALX',
    'ALXN', 'ALXO', 'ALYA', 'AM', 'AMAL', 'AMAT', 'AMBA', 'AMBC', 'AMBC.WS',
    'AMBO', 'AMC', 'AMCI', 'AMCIU', 'AMCIW', 'AMCR', 'AMCX', 'AMD', 'AME',
    'AMED', 'AMEH', 'AMER', 'AMG', 'AMGN', 'AMH', 'AMH.PRD', 'AMH.PRE',
    'AMH.PRF', 'AMH.PRG', 'AMH.PRH', 'AMHC', 'AMHCU', 'AMHCW', 'AMK', 'AMKR',
    'AMN', 'AMNB', 'AMOT', 'AMOV', 'AMP', 'AMPE', 'AMPH', 'AMPY', 'AMRB',
    'AMRC', 'AMRK', 'AMRN', 'AMRS', 'AMRX', 'AMS', 'AMSC', 'AMSF', 'AMST',
    'AMSWA', 'AMT', 'AMTB', 'AMTBB', 'AMTI', 'AMTX', 'AMWD', 'AMWL', 'AMX',
    'AMYT', 'AMZN', 'AN', 'ANAB', 'ANAT', 'ANCN', 'ANDA', 'ANDAR', 'ANDAU',
    'ANDAW', 'ANDE', 'ANET', 'ANF', 'ANGI', 'ANGO', 'ANH', 'ANH.PRA',
    'ANH.PRB', 'ANH.PRC', 'ANIK', 'ANIP', 'ANIX', 'ANNX', 'ANPC', 'ANSS',
    'ANTE', 'ANTM', 'ANVS', 'ANY', 'AOD', 'AON', 'AONE', 'AONE.U', 'AONE.WS',
    'AOS', 'AOSL', 'AOUT', 'AP', 'AP.WS', 'APA', 'APAM', 'APD', 'APDN', 'APEI',
    'APEN', 'APG', 'APH', 'APHA', 'API', 'APLE', 'APLS', 'APLT', 'APM', 'APO',
    'APO.PRA', 'APO.PRB', 'APOG', 'APOP', 'APOPW', 'APPF', 'APPN', 'APPS',
    'APRE', 'APRN', 'APSG', 'APSG.U', 'APSG.WS', 'APT', 'APTO', 'APTS', 'APTV',
    'APTV.PRA', 'APTX', 'APVO', 'APWC', 'APXT', 'APXTU', 'APXTW', 'APYX',
    'AQB', 'AQMS', 'AQN', 'AQNA', 'AQNB', 'AQST', 'AQUA', 'AR', 'ARA', 'ARAV',
    'ARAY', 'ARBGU', 'ARC', 'ARCB', 'ARCC', 'ARCE', 'ARCH', 'ARCO', 'ARCT',
    'ARD', 'ARDC', 'ARDS', 'ARDX', 'ARE', 'AREC', 'ARES', 'ARES.PRA', 'ARGD',
    'ARGO', 'ARGO.PRA', 'ARGX', 'ARI', 'ARKO', 'ARKOW', 'ARKR', 'ARL', 'ARLO',
    'ARLP', 'ARMK', 'ARMP', 'ARNA', 'ARNC', 'AROC', 'AROW', 'ARPO', 'ARQT',
    'ARR', 'ARR.PRC', 'ARRY', 'ARTL', 'ARTLW', 'ARTNA', 'ARTW', 'ARVN', 'ARW',
    'ARWR', 'ARYA', 'ASA', 'ASAN', 'ASAQ', 'ASAQ.U', 'ASAQ.WS', 'ASB',
    'ASB.PRC', 'ASB.PRD', 'ASB.PRE', 'ASB.PRF', 'ASC', 'ASG', 'ASGI', 'ASGN',
    'ASH', 'ASIX', 'ASLE', 'ASLEW', 'ASLN', 'ASM', 'ASMB', 'ASML', 'ASND',
    'ASO', 'ASPL', 'ASPL.U', 'ASPL.WS', 'ASPN', 'ASPS', 'ASPU', 'ASR', 'ASRT',
    'ASRV', 'ASRVP', 'ASTC', 'ASTE', 'ASUR', 'ASX', 'ASYS', 'AT', 'ATA.U',
    'ATAC', 'ATAC.U', 'ATAC.WS', 'ATAX', 'ATCO', 'ATCO.PRD', 'ATCO.PRE',
    'ATCO.PRG', 'ATCO.PRH', 'ATCO.PRI', 'ATCX', 'ATEC', 'ATEN', 'ATEX', 'ATGE',
    'ATH', 'ATH.PRA', 'ATH.PRB', 'ATH.PRC', 'ATH.PRD', 'ATHA', 'ATHE', 'ATHM',
    'ATHX', 'ATI', 'ATIF', 'ATKR', 'ATLC', 'ATLO', 'ATNF', 'ATNFW', 'ATNI',
    'ATNM', 'ATNX', 'ATO', 'ATOM', 'ATOS', 'ATR', 'ATRA', 'ATRC', 'ATRI',
    'ATRO', 'ATRS', 'ATSG', 'ATTO', 'ATUS', 'ATV', 'ATVI', 'ATXI', 'AU', 'AUB',
    'AUBAP', 'AUBN', 'AUDC', 'AUGZ', 'AUMN', 'AUPH', 'AUTL', 'AUTO', 'AUUD',
    'AUUDW', 'AUVI', 'AUY', 'AVA', 'AVAL', 'AVAN', 'AVAN.U', 'AVAN.WS', 'AVAV',
    'AVB', 'AVCO', 'AVCT', 'AVCTW', 'AVD', 'AVDG', 'AVDL', 'AVDR', 'AVEO',
    'AVGO', 'AVGOP', 'AVGR', 'AVID', 'AVIR', 'AVK', 'AVLR', 'AVNS', 'AVNT',
    'AVNW', 'AVO', 'AVRO', 'AVT', 'AVTR', 'AVTR.PRA', 'AVXL', 'AVY', 'AVYA',
    'AWF', 'AWH', 'AWI', 'AWK', 'AWP', 'AWR', 'AWRE', 'AWX', 'AX', 'AXAS',
    'AXDX', 'AXGN', 'AXL', 'AXLA', 'AXNX', 'AXO', 'AXP', 'AXR', 'AXS',
    'AXS.PRE', 'AXSM', 'AXTA', 'AXTI', 'AXU', 'AY', 'AYI', 'AYLA', 'AYRO',
    'AYTU', 'AYTUP', 'AYX', 'AZEK', 'AZN', 'AZO', 'AZPN', 'AZRE', 'AZRX',
    'AZUL', 'AZYO', 'AZZ', 'B', 'BA', 'BABA', 'BAC', 'BAC.PRA', 'BAC.PRB',
    'BAC.PRC', 'BAC.PRE', 'BAC.PRK', 'BAC.PRL', 'BAC.PRM', 'BAC.PRN',
    'BAC.PRO', 'BAF', 'BAH', 'BAK', 'BALY', 'BAM', 'BAMH', 'BAMI', 'BANC',
    'BANC.PRD', 'BANC.PRE', 'BAND', 'BANF', 'BANFP', 'BANR', 'BANX', 'BAP',
    'BASI', 'BATL', 'BATRA', 'BATRK', 'BAX', 'BB', 'BBAR', 'BBBY', 'BBCP',
    'BBD', 'BBDC', 'BBDO', 'BBF', 'BBGI', 'BBI', 'BBIG', 'BBIO', 'BBK', 'BBL',
    'BBN', 'BBQ', 'BBRX', 'BBSI', 'BBU', 'BBVA', 'BBW', 'BBY', 'BC', 'BC.PRA',
    'BC.PRB', 'BC.PRC', 'BCAB', 'BCAC', 'BCACU', 'BCACW', 'BCAT', 'BCBP',
    'BCC', 'BCDA', 'BCDAW', 'BCE', 'BCEI', 'BCEL', 'BCH', 'BCLI', 'BCML',
    'BCO', 'BCOR', 'BCOV', 'BCOW', 'BCPC', 'BCRX', 'BCS', 'BCSF', 'BCTG',
    'BCTX', 'BCTXW', 'BCV', 'BCV.PRA', 'BCX', 'BCYC', 'BDC', 'BDGE', 'BDJ',
    'BDL', 'BDN', 'BDR', 'BDSI', 'BDSX', 'BDTX', 'BDX', 'BDXB', 'BE', 'BEAM',
    'BEAT', 'BECN', 'BEDU', 'BEEM', 'BEEMW', 'BEKE', 'BELFA', 'BELFB', 'BEN',
    'BENE', 'BENER', 'BENEU', 'BENEW', 'BEP', 'BEP.PRA', 'BEPC', 'BERY',
    'BEST', 'BF/A', 'BF/B', 'BFAM', 'BFC', 'BFI', 'BFIIW', 'BFIN', 'BFK',
    'BFRA', 'BFS', 'BFS.PRD', 'BFS.PRE', 'BFST', 'BFT', 'BFT.U', 'BFT.WS',
    'BFY', 'BFZ', 'BG', 'BGB', 'BGCP', 'BGFV', 'BGH', 'BGI', 'BGIO', 'BGNE',
    'BGR', 'BGS', 'BGSF', 'BGT', 'BGX', 'BGY', 'BH', 'BH.A', 'BHAT', 'BHB',
    'BHC', 'BHE', 'BHF', 'BHFAL', 'BHFAN', 'BHFAO', 'BHFAP', 'BHK', 'BHLB',
    'BHP', 'BHR', 'BHR.PRB', 'BHR.PRD', 'BHSE', 'BHSEU', 'BHSEW', 'BHTG',
    'BHV', 'BHVN', 'BIDU', 'BIF', 'BIG', 'BIGC', 'BIIB', 'BILI', 'BILL',
    'BIMI', 'BIO', 'BIO/B', 'BIOC', 'BIOL', 'BIOX', 'BIP', 'BIP.PRA', 'BIPC',
    'BIT', 'BIVI', 'BJ', 'BJRI', 'BK', 'BKCC', 'BKD', 'BKE', 'BKEP', 'BKEPP',
    'BKH', 'BKI', 'BKN', 'BKNG', 'BKR', 'BKSC', 'BKT', 'BKTI', 'BKU', 'BKYI',
    'BL', 'BLBD', 'BLCM', 'BLCT', 'BLD', 'BLDG', 'BLDP', 'BLDR', 'BLE', 'BLFS',
    'BLI', 'BLIN', 'BLK', 'BLKB', 'BLL', 'BLMN', 'BLNK', 'BLNKW', 'BLPH',
    'BLRX', 'BLSA', 'BLU', 'BLUE', 'BLUWU', 'BLW', 'BLX', 'BMA', 'BMAR', 'BME',
    'BMEZ', 'BMI', 'BML.PRG', 'BML.PRH', 'BML.PRJ', 'BML.PRL', 'BMO', 'BMRA',
    'BMRC', 'BMRN', 'BMTC', 'BMY', 'BNED', 'BNFT', 'BNGO', 'BNGOW', 'BNL',
    'BNR', 'BNS', 'BNSO', 'BNTC', 'BNTX', 'BNY', 'BOAC', 'BOAC.U', 'BOAC.WS',
    'BOCH', 'BOE', 'BOH', 'BOKF', 'BOKFL', 'BOMN', 'BOOM', 'BOOT', 'BORR',
    'BOSC', 'BOTJ', 'BOWX', 'BOWXU', 'BOWXW', 'BOX', 'BOXL', 'BP', 'BPFH',
    'BPMC', 'BPMP', 'BPOP', 'BPOPM', 'BPOPN', 'BPRN', 'BPT', 'BPTH', 'BPY',
    'BPYPN', 'BPYPO', 'BPYPP', 'BPYU', 'BPYUP', 'BQ', 'BR', 'BRBR', 'BRBS',
    'BRC', 'BREZ', 'BREZR', 'BREZW', 'BRFS', 'BRG', 'BRG.PRA', 'BRG.PRC',
    'BRG.PRD', 'BRID', 'BRK/A', 'BRK/B', 'BRKL', 'BRKR', 'BRKS', 'BRLI',
    'BRLIR', 'BRLIU', 'BRLIW', 'BRMK', 'BRMK.WS', 'BRN', 'BRO', 'BROG',
    'BROGW', 'BRP', 'BRPA', 'BRPAR', 'BRPAU', 'BRPAW', 'BRQS', 'BRT', 'BRX',
    'BRY', 'BSA', 'BSAC', 'BSBK', 'BSBR', 'BSD', 'BSE', 'BSET', 'BSGM', 'BSIG',
    'BSL', 'BSM', 'BSMX', 'BSN', 'BSN.U', 'BSN.WS', 'BSQR', 'BSRR', 'BST',
    'BSTZ', 'BSVN', 'BSX', 'BSX.PRA', 'BSY', 'BTA', 'BTAI', 'BTAQ', 'BTAQU',
    'BTAQW', 'BTBT', 'BTG', 'BTI', 'BTN', 'BTO', 'BTT', 'BTU', 'BTWN', 'BTWNU',
    'BTWNW', 'BTZ', 'BUD', 'BUFF', 'BUI', 'BUR', 'BURL', 'BUSE', 'BV', 'BVH',
    'BVN', 'BVXV', 'BW', 'BWA', 'BWAC', 'BWACU', 'BWACW', 'BWAY', 'BWB',
    'BWEN', 'BWFG', 'BWG', 'BWL/A', 'BWMX', 'BWXT', 'BX', 'BXC', 'BXG', 'BXMT',
    'BXMX', 'BXP', 'BXP.PRB', 'BXRX', 'BXS', 'BXS.PRA', 'BY', 'BYD', 'BYFC',
    'BYM', 'BYND', 'BYSI', 'BZH', 'BZM', 'BZUN', 'C', 'C.PRJ', 'C.PRK',
    'C.PRN', 'C.PRS', 'CAAP', 'CAAS', 'CABA', 'CABO', 'CAC', 'CACC', 'CACI',
    'CADE', 'CAE', 'CAF', 'CAG', 'CAH', 'CAI', 'CAI.PRA', 'CAI.PRB', 'CAJ',
    'CAKE', 'CAL', 'CALA', 'CALB', 'CALM', 'CALT', 'CALX', 'CAMP', 'CAMT',
    'CAN', 'CANF', 'CANG', 'CAP.U', 'CAPA', 'CAPAU', 'CAPAW', 'CAPL', 'CAPR',
    'CAR', 'CARA', 'CARE', 'CARG', 'CARR', 'CARS', 'CARV', 'CAS.U', 'CASA',
    'CASH', 'CASI', 'CASS', 'CASY', 'CAT', 'CATB', 'CATC', 'CATM', 'CATO',
    'CATY', 'CB', 'CBAH.U', 'CBAN', 'CBAT', 'CBAY', 'CBB', 'CBB.PRB', 'CBD',
    'CBFV', 'CBH', 'CBIO', 'CBLI', 'CBMB', 'CBMG', 'CBNK', 'CBOE', 'CBPO',
    'CBRE', 'CBRL', 'CBSH', 'CBT', 'CBTG', 'CBTX', 'CBU', 'CBZ', 'CC', 'CCAC',
    'CCAC.U', 'CCAC.WS', 'CCAP', 'CCB', 'CCBG', 'CCC', 'CCCC', 'CCD', 'CCEP',
    'CCF', 'CCI', 'CCIV', 'CCIV.U', 'CCIV.WS', 'CCJ', 'CCK', 'CCL', 'CCLP',
    'CCM', 'CCMP', 'CCNC', 'CCNE', 'CCNEP', 'CCO', 'CCOI', 'CCRC', 'CCRN',
    'CCS', 'CCU', 'CCV.U', 'CCX', 'CCX.U', 'CCX.WS', 'CCXI', 'CCZ', 'CD',
    'CDAK', 'CDAY', 'CDE', 'CDEV', 'CDK', 'CDLX', 'CDMO', 'CDMOP', 'CDNA',
    'CDNS', 'CDOR', 'CDR', 'CDR.PRB', 'CDR.PRC', 'CDTX', 'CDW', 'CDXC', 'CDXS',
    'CDZI', 'CE', 'CEA', 'CECE', 'CEE', 'CEI', 'CEIX', 'CEL', 'CELC',
    'CELG.RT', 'CELH', 'CELP', 'CEM', 'CEMI', 'CEN', 'CENT', 'CENTA', 'CENX',
    'CEO', 'CEPU', 'CEQP', 'CEQP.PR', 'CERC', 'CERE', 'CEREW', 'CERN', 'CERS',
    'CERT', 'CET', 'CETX', 'CETXP', 'CETXW', 'CEV', 'CEVA', 'CF', 'CFAC',
    'CFACU', 'CFACW', 'CFB', 'CFBI', 'CFBK', 'CFCV', 'CFFI', 'CFFN', 'CFG',
    'CFG.PRD', 'CFG.PRE', 'CFII', 'CFIIU', 'CFIIW', 'CFIVU', 'CFMS', 'CFR',
    'CFR.PRB', 'CFRX', 'CFX', 'CFXA', 'CG', 'CGA', 'CGBD', 'CGC', 'CGEN',
    'CGIX', 'CGNX', 'CGO', 'CGRO', 'CGROU', 'CGROW', 'CHA', 'CHAQ', 'CHAQ.U',
    'CHAQ.WS', 'CHCI', 'CHCO', 'CHCT', 'CHD', 'CHDN', 'CHE', 'CHEF', 'CHEK',
    'CHEKZ', 'CHFS', 'CHFW.U', 'CHGG', 'CHH', 'CHI', 'CHKP', 'CHL', 'CHMA',
    'CHMG', 'CHMI', 'CHMI.PRA', 'CHMI.PRB', 'CHN', 'CHNG', 'CHNGU', 'CHNR',
    'CHPM', 'CHPMU', 'CHPMW', 'CHRA', 'CHRS', 'CHRW', 'CHS', 'CHSCL', 'CHSCM',
    'CHSCN', 'CHSCO', 'CHSCP', 'CHT', 'CHTR', 'CHU', 'CHUY', 'CHW', 'CHWY',
    'CHX', 'CHY', 'CI', 'CIA', 'CIB', 'CIDM', 'CIEN', 'CIF', 'CIG', 'CIG.C',
    'CIGI', 'CIH', 'CII', 'CIIC', 'CIICU', 'CIICW', 'CIK', 'CIM', 'CIM.PRA',
    'CIM.PRB', 'CIM.PRC', 'CIM.PRD', 'CINF', 'CINR', 'CIO', 'CIO.PRA', 'CIR',
    'CIT', 'CIT.PRB', 'CIVB', 'CIX', 'CIXX', 'CIZN', 'CJJD', 'CKH', 'CKPT',
    'CKX', 'CL', 'CLA', 'CLA.U', 'CLA.WS', 'CLAR', 'CLB', 'CLBK', 'CLBS',
    'CLCT', 'CLDB', 'CLDR', 'CLDT', 'CLDX', 'CLEU', 'CLF', 'CLFD', 'CLGN',
    'CLGX', 'CLH', 'CLI', 'CLII', 'CLII.U', 'CLII.WS', 'CLIR', 'CLLS', 'CLM',
    'CLMT', 'CLNC', 'CLNE', 'CLNN', 'CLNNW', 'CLNY', 'CLNY.PRG', 'CLNY.PRH',
    'CLNY.PRI', 'CLNY.PRJ', 'CLPR', 'CLPS', 'CLPT', 'CLR', 'CLRB', 'CLRBZ',
    'CLRO', 'CLS', 'CLSD', 'CLSK', 'CLSN', 'CLVR', 'CLVRW', 'CLVS', 'CLW',
    'CLWT', 'CLX', 'CLXT', 'CM', 'CMA', 'CMBM', 'CMC', 'CMCL', 'CMCM', 'CMCO',
    'CMCSA', 'CMCT', 'CMCTP', 'CMD', 'CME', 'CMFNL', 'CMG', 'CMI', 'CMLF',
    'CMLFU', 'CMLFW', 'CMLS', 'CMO', 'CMO.PRE', 'CMP', 'CMPI', 'CMPR', 'CMPS',
    'CMPX', 'CMRE', 'CMRE.PRB', 'CMRE.PRC', 'CMRE.PRD', 'CMRE.PRE', 'CMRX',
    'CMS', 'CMS.PRB', 'CMSA', 'CMSC', 'CMSD', 'CMT', 'CMTL', 'CMU', 'CNA',
    'CNBKA', 'CNC', 'CNCE', 'CND.U', 'CNDT', 'CNET', 'CNF', 'CNFR', 'CNFRL',
    'CNHI', 'CNI', 'CNK', 'CNMD', 'CNNB', 'CNNE', 'CNO', 'CNO.PRA', 'CNOB',
    'CNP', 'CNP.PRB', 'CNQ', 'CNR', 'CNS', 'CNSL', 'CNSP', 'CNST', 'CNTG',
    'CNTX', 'CNTY', 'CNX', 'CNXC', 'CNXN', 'CO', 'COCP', 'CODA', 'CODI',
    'CODI.PRA', 'CODI.PRB', 'CODI.PRC', 'CODX', 'COE', 'COF', 'COF.PRG',
    'COF.PRH', 'COF.PRI', 'COF.PRJ', 'COF.PRK', 'COFS', 'COG', 'COGT', 'COHN',
    'COHR', 'COHU', 'COKE', 'COLB', 'COLD', 'COLL', 'COLM', 'COMM', 'COMS',
    'COMSW', 'CONE', 'CONN', 'CONX', 'CONXU', 'CONXW', 'COO', 'COOLU', 'COOP',
    'COP', 'COR', 'CORE', 'CORR', 'CORR.PRA', 'CORT', 'COST', 'COTY', 'COUP',
    'COWN', 'COWNL', 'COWNZ', 'CP', 'CPA', 'CPAC', 'CPAH', 'CPB', 'CPE', 'CPF',
    'CPG', 'CPHC', 'CPHI', 'CPIX', 'CPK', 'CPLG', 'CPLP', 'CPRI', 'CPRT',
    'CPRX', 'CPS', 'CPSH', 'CPSI', 'CPSR', 'CPSR.U', 'CPSR.WS', 'CPSS', 'CPST',
    'CPT', 'CPTA', 'CPTAG', 'CPTAL', 'CPTI', 'CPZ', 'CQP', 'CR', 'CRAI',
    'CRBP', 'CRC', 'CRD/A', 'CRD/B', 'CRDF', 'CREE', 'CREG', 'CRESY', 'CREX',
    'CREXW', 'CRF', 'CRH', 'CRHC', 'CRHC.U', 'CRHC.WS', 'CRHM', 'CRI', 'CRIS',
    'CRK', 'CRL', 'CRM', 'CRMD', 'CRMT', 'CRNC', 'CRNT', 'CRNX', 'CRON',
    'CROX', 'CRS', 'CRSA', 'CRSAU', 'CRSAW', 'CRSP', 'CRSR', 'CRT', 'CRTD',
    'CRTDW', 'CRTO', 'CRTX', 'CRU.U', 'CRUS', 'CRVL', 'CRVS', 'CRWD', 'CRWS',
    'CRY', 'CS', 'CSBR', 'CSCO', 'CSCW', 'CSGP', 'CSGS', 'CSII', 'CSIQ', 'CSL',
    'CSLT', 'CSOD', 'CSPI', 'CSPR', 'CSQ', 'CSR', 'CSR.PRC', 'CSSE', 'CSSEN',
    'CSSEP', 'CSTE', 'CSTL', 'CSTM', 'CSTR', 'CSU', 'CSV', 'CSWC', 'CSWCL',
    'CSWI', 'CSX', 'CTA.PRA', 'CTA.PRB', 'CTAA', 'CTAC', 'CTAC.U', 'CTAC.WS',
    'CTAQU', 'CTAS', 'CTB', 'CTBB', 'CTBI', 'CTDD', 'CTEK', 'CTG', 'CTHR',
    'CTIB', 'CTIC', 'CTK', 'CTLT', 'CTMX', 'CTO', 'CTR', 'CTRA', 'CTRE',
    'CTRM', 'CTRN', 'CTS', 'CTSH', 'CTSO', 'CTT', 'CTVA', 'CTXR', 'CTXRW',
    'CTXS', 'CUB', 'CUBA', 'CUBB', 'CUBE', 'CUBI', 'CUBI.PRC', 'CUBI.PRD',
    'CUBI.PRE', 'CUBI.PRF', 'CUE', 'CUK', 'CULP', 'CURI', 'CURIW', 'CURO',
    'CUTR', 'CUZ', 'CVA', 'CVAC', 'CVBF', 'CVCO', 'CVCY', 'CVE', 'CVEO',
    'CVET', 'CVGI', 'CVGW', 'CVI', 'CVLB', 'CVLG', 'CVLT', 'CVLY', 'CVM',
    'CVNA', 'CVR', 'CVS', 'CVU', 'CVV', 'CVX', 'CW', 'CWBC', 'CWBR', 'CWCO',
    'CWEN', 'CWEN.A', 'CWH', 'CWK', 'CWST', 'CWT', 'CX', 'CXDC', 'CXDO', 'CXE',
    'CXH', 'CXO', 'CXP', 'CXW', 'CYAD', 'CYAN', 'CYBE', 'CYBR', 'CYCC',
    'CYCCP', 'CYCN', 'CYD', 'CYH', 'CYRN', 'CYRX', 'CYTH', 'CYTHW', 'CYTK',
    'CZNC', 'CZR', 'CZWI', 'CZZ', 'D', 'DAC', 'DADA', 'DAIO', 'DAKT', 'DAL',
    'DAN', 'DAO', 'DAR', 'DARE', 'DASH', 'DAUG', 'DAVA', 'DB', 'DBD', 'DBDR',
    'DBDRU', 'DBDRW', 'DBI', 'DBJA', 'DBL', 'DBOC', 'DBVT', 'DBX', 'DCBO',
    'DCF', 'DCI', 'DCO', 'DCOM', 'DCOMP', 'DCP', 'DCP.PRB', 'DCP.PRC', 'DCPH',
    'DCRB', 'DCRBU', 'DCRBW', 'DCT', 'DCTH', 'DCUE', 'DD', 'DDD', 'DDEC',
    'DDF', 'DDI', 'DDMXU', 'DDOG', 'DDS', 'DDT', 'DE', 'DEA', 'DECK', 'DECZ',
    'DEFN', 'DEH', 'DEH.U', 'DEH.WS', 'DEI', 'DELL', 'DEN', 'DENN', 'DEO',
    'DESP', 'DEX', 'DFEB', 'DFFN', 'DFHT', 'DFHTU', 'DFHTW', 'DFHY', 'DFIN',
    'DFNS', 'DFNS.U', 'DFNS.WS', 'DFNV', 'DFP', 'DFPH', 'DFPHU', 'DFPHW',
    'DFS', 'DG', 'DGICA', 'DGICB', 'DGII', 'DGLY', 'DGNR', 'DGNR.U', 'DGNR.WS',
    'DGNS', 'DGX', 'DHC', 'DHCNI', 'DHCNL', 'DHF', 'DHI', 'DHIL', 'DHR',
    'DHR.PRA', 'DHR.PRB', 'DHT', 'DHX', 'DHY', 'DIAX', 'DIN', 'DIOD', 'DIS',
    'DISCA', 'DISCB', 'DISCK', 'DISH', 'DIT', 'DJCO', 'DJUL', 'DJUN', 'DK',
    'DKL', 'DKNG', 'DKS', 'DL', 'DLA', 'DLB', 'DLHC', 'DLNG', 'DLNG.PRA',
    'DLNG.PRB', 'DLPN', 'DLR', 'DLR.PRC', 'DLR.PRJ', 'DLR.PRK', 'DLR.PRL',
    'DLTH', 'DLTR', 'DLX', 'DLY', 'DM', 'DM.WS', 'DMAC', 'DMAY', 'DMB', 'DMF',
    'DMLP', 'DMO', 'DMRC', 'DMS', 'DMS.WS', 'DMTK', 'DMYD', 'DMYD.U',
    'DMYD.WS', 'DMYI', 'DMYI.U', 'DMYI.WS', 'DNB', 'DNK', 'DNLI', 'DNMR',
    'DNMR.WS', 'DNN', 'DNOV', 'DNOW', 'DNP', 'DOC', 'DOCT', 'DOCU', 'DOGZ',
    'DOMO', 'DOOO', 'DOOR', 'DORM', 'DOV', 'DOW', 'DOX', 'DOYU', 'DPG', 'DPW',
    'DPZ', 'DQ', 'DRD', 'DRE', 'DRH', 'DRH.PRA', 'DRI', 'DRIO', 'DRIOW',
    'DRMT', 'DRNA', 'DRQ', 'DRRX', 'DRTT', 'DRUA', 'DS', 'DS.PRB', 'DS.PRC',
    'DS.PRD', 'DSAC', 'DSACU', 'DSACW', 'DSE', 'DSEP', 'DSGX', 'DSJA', 'DSKE',
    'DSKEW', 'DSL', 'DSM', 'DSOC', 'DSPG', 'DSS', 'DSSI', 'DSU', 'DSWL', 'DSX',
    'DSX.PRB', 'DT', 'DTB', 'DTE', 'DTEA', 'DTF', 'DTIL', 'DTJ', 'DTLA.PR',
    'DTP', 'DTSS', 'DTW', 'DTY', 'DUC', 'DUDE', 'DUK', 'DUK.PRA', 'DUKB',
    'DUKH', 'DUNEU', 'DUO', 'DUOT', 'DVA', 'DVAX', 'DVD', 'DVN', 'DWIN.U',
    'DWSN', 'DX', 'DX.PRB', 'DX.PRC', 'DXC', 'DXCM', 'DXF', 'DXPE', 'DXR',
    'DXYN', 'DY', 'DYAI', 'DYFN', 'DYN', 'DYNT', 'DZSI', 'E', 'EA', 'EAD',
    'EAF', 'EAI', 'EAR', 'EARN', 'EARS', 'EAST', 'EAT', 'EB', 'EBAY', 'EBAYL',
    'EBC', 'EBF', 'EBIX', 'EBMT', 'EBON', 'EBR', 'EBR.B', 'EBS', 'EBSB', 'EBTC',
    'EC', 'ECC           ', 'ECCB', 'ECCX', 'ECCY', 'ECF', 'ECF.PRA', 'ECHO',
    'ECL', 'ECOL', 'ECOLW', 'ECOM          ', 'ECOR', 'ECPG', 'ED', 'EDAP',
    'EDD', 'EDF', 'EDI', 'EDIT', 'EDN', 'EDRY', 'EDSA', 'EDTK', 'EDTXU', 'EDU',
    'EDUC', 'EEA', 'EEFT', 'EEX', 'EFC', 'EFC.PRA', 'EFF', 'EFL', 'EFOI',
    'EFR', 'EFSC', 'EFT', 'EFX', 'EGAN', 'EGBN', 'EGF', 'EGHT', 'EGIS', 'EGLE',
    'EGO', 'EGOV', 'EGP', 'EGRX', 'EGY', 'EH', 'EHC', 'EHI', 'EHT', 'EHTH',
    'EIC', 'EIDX', 'EIG', 'EIGI', 'EIGR', 'EIM', 'EIX', 'EKSO', 'EL', 'ELA',
    'ELAN', 'ELAT', 'ELC', 'ELDN', 'ELF', 'ELLO', 'ELMD', 'ELOX', 'ELP', 'ELS',
    'ELSE', 'ELTK', 'ELVT', 'ELY', 'ELYS', 'EMAN', 'EMCF', 'EMD', 'EME', 'EMF',
    'EMKR', 'EML', 'EMN', 'EMO', 'EMP', 'EMPW', 'EMPW.U', 'EMPW.WS', 'EMR',
    'EMX', 'ENB', 'ENBA', 'ENBL', 'ENDP', 'ENG', 'ENIA', 'ENIC', 'ENJ', 'ENLC',
    'ENLV', 'ENO', 'ENOB', 'ENPC', 'ENPC.U', 'ENPC.WS', 'ENPH', 'ENR',
    'ENR.PRA', 'ENS', 'ENSG', 'ENSV', 'ENTA', 'ENTG', 'ENTX', 'ENTXW', 'ENV',
    'ENVA', 'ENVB', 'ENX', 'ENZ', 'EOD', 'EOG', 'EOI', 'EOLS', 'EOS', 'EOSE',
    'EOSEW', 'EOT', 'EP.PRC', 'EPAC', 'EPAM', 'EPAY', 'EPC', 'EPD', 'EPIX',
    'EPM', 'EPR', 'EPR.PRC', 'EPR.PRE', 'EPR.PRG', 'EPRT', 'EPSN', 'EPZM',
    'EQ', 'EQBK', 'EQC', 'EQC.PRD', 'EQD', 'EQD.U', 'EQD.WS', 'EQH', 'EQH.PRA',
    'EQIX', 'EQNR', 'EQOS', 'EQOSW', 'EQR', 'EQS', 'EQT', 'EQX', 'ERC', 'ERES',
    'ERESU', 'ERESW', 'ERF', 'ERH', 'ERIC', 'ERIE', 'ERII', 'ERJ', 'ERYP',
    'ES', 'ESBK', 'ESCA', 'ESE', 'ESEA', 'ESGC', 'ESGR', 'ESGRO', 'ESGRP',
    'ESI', 'ESLT', 'ESNT', 'ESP', 'ESPR', 'ESQ', 'ESRT', 'ESS', 'ESSA', 'ESSC',
    'ESSCR', 'ESSCU', 'ESSCW', 'ESTA', 'ESTC', 'ESTE', 'ESXB', 'ET', 'ETAC',
    'ETACU', 'ETACW', 'ETB', 'ETG', 'ETH', 'ETI.PR', 'ETJ', 'ETM', 'ETN',
    'ETNB', 'ETO', 'ETON', 'ETP.PRC', 'ETP.PRD', 'ETP.PRE', 'ETR', 'ETRN',
    'ETSY', 'ETTX', 'ETV', 'ETW', 'ETX           ', 'ETY', 'EUCG', 'EUCR',
    'EUCRU', 'EUCRW', 'EURN', 'EV', 'EVA', 'EVBG', 'EVBN', 'EVC', 'EVER',
    'EVF', 'EVFM', 'EVG', 'EVGBC', 'EVGN', 'EVH', 'EVI', 'EVK', 'EVLO', 'EVM',
    'EVN', 'EVOK', 'EVOL', 'EVOP', 'EVR', 'EVRG', 'EVRI', 'EVT', 'EVTC', 'EVV',
    'EVY', 'EW', 'EWBC', 'EXAS', 'EXC', 'EXD', 'EXEL', 'EXFO', 'EXG', 'EXK',
    'EXLS', 'EXN', 'EXP', 'EXPC', 'EXPCU', 'EXPCW', 'EXPD', 'EXPE', 'EXPI',
    'EXPO', 'EXPR', 'EXR', 'EXTN', 'EXTR', 'EYE', 'EYEG', 'EYEN', 'EYES',
    'EYESW', 'EYPT', 'EZPW', 'F', 'F.PRB', 'F.PRC', 'FAF', 'FAII', 'FAII.U',
    'FAII.WS', 'FAM', 'FAMI', 'FANG', 'FANH', 'FARM', 'FARO', 'FAST', 'FAT',
    'FATBP', 'FATBW', 'FATE', 'FAUG', 'FAX', 'FB', 'FBC', 'FBHS', 'FBIO',
    'FBIOP', 'FBIZ', 'FBK', 'FBM', 'FBMS', 'FBNC', 'FBP', 'FBRX', 'FBSS', 'FC',
    'FCAC', 'FCACU', 'FCACW', 'FCAP', 'FCAU', 'FCBC', 'FCBP', 'FCCO', 'FCCY',
    'FCEL', 'FCF', 'FCFS', 'FCN', 'FCNCA', 'FCNCP', 'FCO', 'FCPT', 'FCRD',
    'FCRW', 'FCRZ', 'FCT', 'FCX', 'FDBC', 'FDEC', 'FDEU', 'FDG', 'FDMT', 'FDP',
    'FDS', 'FDUS', 'FDUSG', 'FDUSL', 'FDUSZ', 'FDX', 'FE', 'FEDU', 'FEDX',
    'FEI           ', 'FEIM', 'FELE', 'FEN', 'FENC', 'FENG', 'FEO', 'FET',
    'FEYE', 'FF', 'FFA', 'FFBC', 'FFBW', 'FFC', 'FFEB', 'FFG', 'FFHL', 'FFIC',
    'FFIN', 'FFIV', 'FFNW', 'FFWM', 'FGB', 'FGBI', 'FGEN', 'FGF', 'FGFPP',
    'FGNA', 'FGNA.U', 'FGNA.WS', 'FHB', 'FHI', 'FHN', 'FHN.PRA', 'FHN.PRB',
    'FHN.PRC', 'FHN.PRD', 'FHN.PRE', 'FHTX', 'FI', 'FIBK', 'FICO', 'FIF',
    'FIII', 'FIIIU', 'FIIIW', 'FINS', 'FINV', 'FIS', 'FISI', 'FISV', 'FIT',
    'FITB', 'FITBI', 'FITBO', 'FITBP', 'FIV', 'FIVE', 'FIVN', 'FIX', 'FIXX',
    'FIZZ', 'FJUL', 'FJUN', 'FL', 'FLACU', 'FLC', 'FLDM', 'FLEX', 'FLGT',
    'FLIC', 'FLIR', 'FLL', 'FLMN', 'FLMNW', 'FLNG', 'FLNT', 'FLO', 'FLOW',
    'FLR', 'FLRZ', 'FLS', 'FLT', 'FLUX', 'FLV', 'FLWR', 'FLWS', 'FLXN', 'FLXS',
    'FLY', 'FMAC', 'FMAC.U', 'FMAC.WS', 'FMAO', 'FMAX', 'FMAY', 'FMBH', 'FMBI',
    'FMBIO', 'FMBIP', 'FMC', 'FMN', 'FMNB', 'FMO', 'FMS', 'FMTX', 'FMX', 'FMY',
    'FN', 'FNB', 'FNB.PRE', 'FNCB', 'FND', 'FNF', 'FNHC', 'FNKO', 'FNLC',
    'FNOV', 'FNV', 'FNWB', 'FOCS', 'FOCT', 'FOE', 'FOF', 'FOLD', 'FONR', 'FOR',
    'FORD', 'FORM', 'FORR', 'FORTY', 'FOSL', 'FOUR', 'FOX', 'FOXA', 'FOXF',
    'FPAC.U', 'FPAY', 'FPF', 'FPH', 'FPI', 'FPI.PRB', 'FPL', 'FPRX', 'FR',
    'FRA', 'FRAF', 'FRBA', 'FRBK', 'FRC', 'FRC.PRG', 'FRC.PRH', 'FRC.PRI',
    'FRC.PRJ', 'FRC.PRK', 'FRD', 'FREE', 'FREEW', 'FREQ', 'FRG', 'FRGAP',
    'FRGI', 'FRHC', 'FRLN', 'FRME', 'FRO', 'FROG', 'FRPH', 'FRPT', 'FRSX',
    'FRT', 'FRT.PRC', 'FRTA', 'FRX.U', 'FSBW', 'FSD', 'FSDC', 'FSEA', 'FSEP',
    'FSFG', 'FSI', 'FSK', 'FSKR', 'FSLF', 'FSLR', 'FSLY', 'FSM', 'FSP', 'FSR',
    'FSR.WS', 'FSRV', 'FSRVU', 'FSRVW', 'FSS', 'FST', 'FST.U', 'FST.WS',
    'FSTR', 'FSTX', 'FSV', 'FT', 'FTAI', 'FTAI.PRA', 'FTAI.PRB', 'FTCH',
    'FTCVU', 'FTDR', 'FTEK', 'FTF', 'FTFT', 'FTHM', 'FTHY', 'FTI', 'FTIV',
    'FTIVU', 'FTIVW', 'FTK', 'FTNT', 'FTOC', 'FTOCU', 'FTOCW', 'FTS', 'FTSI',
    'FTV', 'FTV.PRA', 'FUBO', 'FUL', 'FULC', 'FULT', 'FULTP', 'FUN', 'FUNC',
    'FUND', 'FUNL', 'FURY', 'FUSB', 'FUSE', 'FUSE.U', 'FUSE.WS', 'FUSN',
    'FUTU', 'FUV', 'FVAM', 'FVCB', 'FVE', 'FVRR', 'FVT.U', 'FWONA', 'FWONK',
    'FWP', 'FWRD', 'FXNC', 'G', 'GAB', 'GAB.PRG', 'GAB.PRH', 'GAB.PRJ',
    'GAB.PRK', 'GABC', 'GAIA', 'GAIN', 'GAINL', 'GAINM', 'GALT', 'GAM',
    'GAM.PRB', 'GAN', 'GASS', 'GATO', 'GATX', 'GAU', 'GB', 'GB.WS', 'GBAB',
    'GBCI', 'GBDC', 'GBIO', 'GBL', 'GBLI', 'GBLIL', 'GBLK', 'GBR', 'GBS',
    'GBT', 'GBX', 'GCBC', 'GCI', 'GCMG', 'GCMGW', 'GCO', 'GCP', 'GCV', 'GD',
    'GDDY', 'GDEN', 'GDL', 'GDL.PRC', 'GDO', 'GDOT', 'GDP', 'GDRX', 'GDS',
    'GDV', 'GDV.PRG', 'GDV.PRH', 'GDYN', 'GDYNW', 'GE', 'GECC', 'GECCL',
    'GECCM', 'GECCN', 'GEF', 'GEF.B', 'GEG', 'GEL', 'GEN           ', 'GENC',
    'GENE', 'GEO', 'GEOS', 'GER', 'GERN', 'GES', 'GEVO', 'GF', 'GFED', 'GFF',
    'GFI', 'GFL', 'GFLU', 'GFN', 'GFNCP', 'GFNSL', 'GFNSZ', 'GFX.U', 'GGAL',
    'GGB', 'GGG', 'GGM', 'GGN', 'GGN.PRB', 'GGO', 'GGO.PRA', 'GGT', 'GGT.PRE',
    'GGT.PRG', 'GGZ', 'GGZ.PRA', 'GH', 'GHC', 'GHG', 'GHIV', 'GHIVU', 'GHIVW',
    'GHL', 'GHLD', 'GHM', 'GHSI', 'GHVIU', 'GHY', 'GIB', 'GIFI', 'GIGM',
    'GIII', 'GIK', 'GIK.U', 'GIK.WS', 'GIL', 'GILD', 'GILT', 'GIM', 'GIS',
    'GIX', 'GIX.RT', 'GIX.U', 'GIX.WS', 'GJH', 'GJO', 'GJP', 'GJR', 'GJS',
    'GJT', 'GKOS', 'GL', 'GL.PRC', 'GLAD', 'GLADD', 'GLADL', 'GLAQU', 'GLBS',
    'GLBZ', 'GLDD', 'GLDG', 'GLEO', 'GLEO.U', 'GLEO.WS', 'GLG', 'GLMD', 'GLNG',
    'GLO', 'GLOB', 'GLOG', 'GLOG.PRA', 'GLOP', 'GLOP.PRA', 'GLOP.PRB',
    'GLOP.PRC', 'GLP', 'GLP.PRA', 'GLPG', 'GLPI', 'GLQ', 'GLRE', 'GLSI', 'GLT',
    'GLTO', 'GLU', 'GLU.PRA', 'GLU.PRB', 'GLUU', 'GLV', 'GLW', 'GLYC', 'GM',
    'GMAB', 'GMBL', 'GMBLW', 'GMDA', 'GME', 'GMED', 'GMLP', 'GMLPP', 'GMRE',
    'GMRE.PRA', 'GMS', 'GMTA', 'GMVD', 'GNCA', 'GNE', 'GNE.PRA', 'GNFT', 'GNK',
    'GNL', 'GNL.PRA', 'GNL.PRB', 'GNLN', 'GNMK', 'GNOG', 'GNOGW', 'GNPK.U',
    'GNPX', 'GNRC', 'GNRS', 'GNRSU', 'GNRSW', 'GNSS', 'GNT', 'GNT.PRA', 'GNTX',
    'GNTY', 'GNUS', 'GNW', 'GO', 'GOAC', 'GOAC.U', 'GOAC.WS', 'GOCO', 'GOED',
    'GOEV', 'GOEVW', 'GOF', 'GOGL', 'GOGO', 'GOL', 'GOLD', 'GOLF', 'GOOD',
    'GOODM', 'GOODN', 'GOOG', 'GOOGL', 'GOOS', 'GORO', 'GOSS', 'GOVX', 'GOVXW',
    'GOVZ', 'GP', 'GPC', 'GPI', 'GPJA', 'GPK', 'GPL', 'GPM', 'GPMT', 'GPN',
    'GPP', 'GPRE', 'GPRK', 'GPRO', 'GPS', 'GPX', 'GRA', 'GRAY', 'GRBK', 'GRC',
    'GRCY', 'GRCYU', 'GRCYW', 'GRF', 'GRFS', 'GRIL', 'GRIN', 'GRMN', 'GRNQ',
    'GRNV', 'GRNVR', 'GRNVU', 'GRNVW', 'GROW', 'GRP.U', 'GRPN', 'GRSV',
    'GRSVU', 'GRSVW', 'GRTS', 'GRTX', 'GRUB', 'GRVY', 'GRWG', 'GRX', 'GS',
    'GS.PRA', 'GS.PRC', 'GS.PRD', 'GS.PRJ', 'GS.PRK', 'GS.PRN', 'GSAH',
    'GSAH.U', 'GSAH.WS', 'GSAT', 'GSBC', 'GSBD', 'GSEE', 'GSHD', 'GSID',
    'GSIT', 'GSK', 'GSKY', 'GSL', 'GSL.PRB', 'GSLD', 'GSM', 'GSMG', 'GSMGW',
    'GSS', 'GSUM', 'GSUS', 'GSV', 'GSX', 'GT', 'GTE', 'GTEC', 'GTES', 'GTH',
    'GTHX', 'GTIM', 'GTIP', 'GTLS', 'GTN', 'GTN.A', 'GTS', 'GTT', 'GTY',
    'GTYH', 'GURE', 'GUT', 'GUT.PRA', 'GUT.PRC', 'GVA', 'GVP', 'GWAC', 'GWACW',
    'GWB', 'GWGH', 'GWPH', 'GWRE', 'GWRS', 'GWW', 'GXGX', 'GXGXU', 'GXGXW',
    'GYC', 'GYRO', 'H', 'HA', 'HAACU', 'HAE', 'HAFC', 'HAIN', 'HAL', 'HALL',
    'HALO', 'HAPP', 'HARP', 'HAS', 'HASI', 'HAYN', 'HBAN', 'HBANN', 'HBANO',
    'HBB', 'HBCP', 'HBI', 'HBIO', 'HBM', 'HBMD', 'HBNC', 'HBP', 'HBT', 'HCA',
    'HCAP', 'HCAPZ', 'HCAR', 'HCARU', 'HCARW', 'HCAT', 'HCC', 'HCCI', 'HCDI',
    'HCHC', 'HCI', 'HCKT', 'HCM', 'HCSG', 'HCXY', 'HCXZ', 'HD', 'HDB', 'HDSN',
    'HE', 'HEAR', 'HEC', 'HECCU', 'HECCW', 'HEES', 'HEGD', 'HEI', 'HEI/A',
    'HELE', 'HELX', 'HEP', 'HEPA', 'HEQ', 'HES', 'HESM', 'HEXO', 'HFBL', 'HFC',
    'HFEN', 'HFFG', 'HFRO', 'HFRO.PRA', 'HFWA', 'HGBL', 'HGEN', 'HGH', 'HGLB',
    'HGSH', 'HGV', 'HHC', 'HHR', 'HI', 'HIBB', 'HIE', 'HIFS', 'HIG', 'HIG.PRG',
    'HIGA', 'HIGA.U', 'HIGA.WS', 'HIHO', 'HII', 'HIL', 'HIMX', 'HIO', 'HIW',
    'HIX', 'HJLI', 'HJLIW', 'HKIB', 'HKIT', 'HL', 'HL.PRB', 'HLF', 'HLG',
    'HLI', 'HLIO', 'HLIT', 'HLM.PR', 'HLNE', 'HLT', 'HLX', 'HLXA', 'HMC',
    'HMCOU', 'HMG', 'HMHC', 'HMI', 'HMLP', 'HMLP.PRA', 'HMN', 'HMNF', 'HMST',
    'HMSY', 'HMTV', 'HMY', 'HNGR', 'HNI', 'HNNA', 'HNP', 'HNRG', 'HNW', 'HOFT',
    'HOFV', 'HOFVW', 'HOG', 'HOL', 'HOLI', 'HOLUU', 'HOLUW', 'HOLX', 'HOMB',
    'HOME', 'HON', 'HONE', 'HOOK', 'HOPE', 'HOTH', 'HOV', 'HOVNP', 'HP', 'HPE',
    'HPF', 'HPI', 'HPK', 'HPKEW', 'HPP', 'HPQ', 'HPR', 'HPS', 'HPX', 'HPX.U',
    'HPX.WS', 'HQH', 'HQI', 'HQL', 'HQY', 'HR', 'HRB', 'HRC', 'HRI', 'HRL',
    'HRMY', 'HROW', 'HRTG', 'HRTX', 'HRZN', 'HSAQ', 'HSBC', 'HSBC.PRA', 'HSC',
    'HSDT', 'HSIC', 'HSII', 'HSKA', 'HSON', 'HST', 'HSTM', 'HSTO', 'HSY', 'HT',
    'HT.PRC', 'HT.PRD', 'HT.PRE', 'HTA', 'HTBI', 'HTBK', 'HTBX', 'HTD', 'HTFA',
    'HTGC', 'HTGM', 'HTH', 'HTHT', 'HTIA', 'HTLD', 'HTLF', 'HTLFP', 'HTOO',
    'HTOOW', 'HTPA.U', 'HTY', 'HUBB', 'HUBG', 'HUBS', 'HUGE', 'HUIZ', 'HUM',
    'HUN', 'HURC', 'HURN', 'HUSA', 'HUSN', 'HUYA', 'HVBC', 'HVT', 'HVT/A',
    'HWBK', 'HWC', 'HWCC', 'HWCPL', 'HWCPZ', 'HWKN', 'HWM', 'HWM.PR', 'HX',
    'HXL', 'HY', 'HYB', 'HYFM', 'HYGO', 'HYI', 'HYLN', 'HYMC', 'HYMCW',
    'HYMCZ', 'HYRE', 'HYT', 'HZAC', 'HZAC.U', 'HZAC.WS', 'HZN', 'HZNP', 'HZO',
    'HZON', 'HZON.U', 'HZON.WS', 'IAA', 'IAC', 'IACA', 'IACA.U', 'IACA.WS',
    'IAE', 'IAF', 'IAG', 'IART', 'IBA', 'IBCP', 'IBEX', 'IBHF', 'IBIO', 'IBKR',
    'IBM', 'IBN', 'IBOC', 'IBP', 'IBTX', 'ICAD', 'ICBK', 'ICCC', 'ICCH', 'ICD',
    'ICE', 'ICFI', 'ICHR', 'ICL', 'ICLK', 'ICLR', 'ICMB', 'ICON', 'ICPT',
    'ICUI', 'ID', 'IDA', 'IDCC', 'IDE', 'IDEX', 'IDN', 'IDRA', 'IDT', 'IDXG',
    'IDXX', 'IDYA', 'IEA', 'IEAWW', 'IEC', 'IEP', 'IESC', 'IEX', 'IFF', 'IFFT',
    'IFMK', 'IFN', 'IFRX', 'IFS', 'IGA', 'IGAC', 'IGACU', 'IGACW', 'IGC',
    'IGD', 'IGI', 'IGIC', 'IGICW', 'IGLE', 'IGMS', 'IGR', 'IGT', 'IH', 'IHC',
    'IHD', 'IHG', 'IHIT', 'IHRT', 'IHT', 'IHTA', 'IIAC.U', 'IID', 'IIF', 'III',
    'IIIIU', 'IIIN', 'IIIV', 'IIM', 'IIN', 'IIPR', 'IIPR.PRA', 'IIVI', 'IIVIP',
    'IKNX', 'IKT', 'ILMN', 'ILPT', 'IMAB', 'IMAC', 'IMACW', 'IMAX', 'IMBI',
    'IMGN', 'IMH', 'IMKTA', 'IMMP', 'IMMR', 'IMNM', 'IMO', 'IMOS', 'IMPX',
    'IMPX.U', 'IMPX.WS', 'IMRA', 'IMRN', 'IMRNW', 'IMTE', 'IMTX', 'IMTXW',
    'IMUX', 'IMV', 'IMVT', 'IMXI', 'INAB', 'INAQ', 'INAQU', 'INAQW', 'INBK',
    'INBKL', 'INBKZ', 'INBX', 'INCY', 'INDB', 'INDO', 'INDT', 'INFI', 'INFN',
    'INFO', 'INFU', 'INFY', 'ING', 'INGN', 'INGR', 'INKA', 'INKAU', 'INKAW',
    'INM', 'INMB', 'INMD', 'INN', 'INN.PRD', 'INN.PRE', 'INO', 'INOD', 'INOV',
    'INPX', 'INS', 'INSE', 'INSG', 'INSI', 'INSM', 'INSP', 'INSW', 'INSW.PRA',
    'INT', 'INTC', 'INTG', 'INTT', 'INTU', 'INTZ', 'INUV', 'INVA', 'INVE',
    'INVH', 'INVO', 'INZY', 'IO', 'IONS', 'IOR', 'IOSP', 'IOVA', 'IP', 'IPA',
    'IPAR', 'IPDN', 'IPG', 'IPGP', 'IPHA', 'IPHI', 'IPI', 'IPLDP', 'IPOC',
    'IPOC.U', 'IPOC.WS', 'IPOD', 'IPOD.U', 'IPOD.WS', 'IPOE', 'IPOE.U',
    'IPOE.WS', 'IPOF', 'IPOF.U', 'IPOF.WS', 'IPV', 'IPV.U', 'IPV.WS', 'IPWR',
    'IQ', 'IQI', 'IQV', 'IR', 'IRBT', 'IRCP', 'IRDM', 'IRIX', 'IRL', 'IRM',
    'IRMD', 'IROQ', 'IRR', 'IRS', 'IRT', 'IRTC', 'IRWD', 'ISBC', 'ISD', 'ISDR',
    'ISEE', 'ISIG', 'ISNS', 'ISR', 'ISRG', 'ISSC', 'ISTR', 'IT', 'ITAC',
    'ITACU', 'ITACW', 'ITCB', 'ITCI', 'ITGR', 'ITI', 'ITIC', 'ITMR', 'ITOS',
    'ITP', 'ITRG', 'ITRI', 'ITRM', 'ITRN', 'ITT', 'ITUB', 'ITW', 'IVA', 'IVAC',
    'IVC', 'IVDG', 'IVH', 'IVLC', 'IVR', 'IVR.PRA', 'IVR.PRB', 'IVR.PRC',
    'IVRA', 'IVSG', 'IVZ', 'IX', 'IZEA', 'J', 'JACK', 'JAGX', 'JAKK', 'JAMF',
    'JAN', 'JANZ', 'JAQC', 'JAQCU', 'JAQCW', 'JAX', 'JAZZ', 'JBGS', 'JBHT',
    'JBK', 'JBL', 'JBLU', 'JBSS', 'JBT', 'JCE', 'JCI', 'JCIC', 'JCICU',
    'JCICW', 'JCO', 'JCOM', 'JCS', 'JCTCF', 'JD', 'JDD', 'JE', 'JEF', 'JELD',
    'JEMD', 'JEQ', 'JFIN', 'JFR', 'JFU', 'JG', 'JGH', 'JHAA', 'JHB', 'JHG',
    'JHI', 'JHS', 'JHX', 'JIH', 'JIH.U', 'JIH.WS', 'JILL', 'JJSF', 'JKHY',
    'JKS', 'JLL', 'JLS', 'JMIA', 'JMM', 'JMP', 'JMPNL', 'JMPNZ', 'JNCE', 'JNJ',
    'JNPR', 'JOB', 'JOBS', 'JOE', 'JOF', 'JOUT', 'JP', 'JPC', 'JPI', 'JPM',
    'JPM.PRC', 'JPM.PRD', 'JPM.PRG', 'JPM.PRH', 'JPM.PRJ', 'JPS', 'JPT', 'JQC',
    'JRI', 'JRJC', 'JRO', 'JRS', 'JRSH', 'JRVR', 'JSD', 'JSM', 'JT', 'JTA',
    'JTD', 'JULZ', 'JUPW', 'JUPWW', 'JVA', 'JW/A', 'JW/B', 'JWN', 'JWS',
    'JWS.U', 'JWS.WS', 'JYAC', 'JYNT', 'K', 'KAI', 'KALA', 'KALU', 'KALV',
    'KAMN', 'KAR', 'KB', 'KBAL', 'KBH', 'KBNT', 'KBNTW', 'KBR', 'KBSF', 'KC',
    'KCAPL', 'KDMN', 'KDNY', 'KDP', 'KE', 'KELYA', 'KELYB', 'KEN', 'KEP',
    'KEQU', 'KERN', 'KERNW', 'KEX', 'KEY', 'KEY.PRI', 'KEY.PRJ', 'KEY.PRK',
    'KEYS', 'KF', 'KFFB', 'KFRC', 'KFS', 'KFY', 'KGC', 'KHC', 'KIDS', 'KIM',
    'KIM.PRL', 'KIM.PRM', 'KIN', 'KINS', 'KINZU', 'KIO', 'KIQ', 'KIRK', 'KJUL',
    'KKR', 'KKR.PRA', 'KKR.PRB', 'KKR.PRC', 'KL', 'KLAC', 'KLDO', 'KLIC',
    'KLR', 'KLR.WS', 'KLXE', 'KMB', 'KMDA', 'KMF', 'KMI', 'KMPR', 'KMT', 'KMX',
    'KN', 'KNDI', 'KNGS', 'KNL', 'KNOP', 'KNSA', 'KNSL', 'KNTE', 'KNX', 'KO',
    'KOD', 'KODK', 'KOF', 'KOP', 'KOPN', 'KOR', 'KOS', 'KOSS', 'KPTI', 'KR',
    'KRA', 'KRBP', 'KRC', 'KREF', 'KRG', 'KRKR', 'KRMD', 'KRNT', 'KRNY', 'KRO',
    'KRON', 'KROS', 'KRP', 'KRTX', 'KRUS', 'KRYS', 'KSM', 'KSMT', 'KSMTU',
    'KSMTW', 'KSPN', 'KSS', 'KSU', 'KSU.PR', 'KT', 'KTB', 'KTCC', 'KTF', 'KTH',
    'KTN', 'KTOS', 'KTRA', 'KURA', 'KVHI', 'KW', 'KWAC.U', 'KWR', 'KXIN',
    'KYMR', 'KYN', 'KZIA', 'KZR', 'L', 'LAC', 'LACQ', 'LACQU', 'LACQW', 'LAD',
    'LADR', 'LAIX', 'LAKE', 'LAMR', 'LANC', 'LAND', 'LANDO', 'LANDP', 'LARK',
    'LASR', 'LATN', 'LATNU', 'LATNW', 'LAUR', 'LAWS', 'LAZ', 'LAZR', 'LAZRW',
    'LAZY', 'LB', 'LBAI', 'LBC', 'LBRDA', 'LBRDK', 'LBRDP', 'LBRT', 'LBTYA',
    'LBTYB', 'LBTYK', 'LC', 'LCAP', 'LCAPU', 'LCAPW', 'LCI', 'LCII', 'LCNB',
    'LCTX', 'LCUT', 'LCY', 'LCYAU', 'LCYAW', 'LDL', 'LDOS', 'LDP', 'LE', 'LEA',
    'LEAF', 'LEAP', 'LEAP.U', 'LEAP.WS', 'LECO', 'LEDS', 'LEE', 'LEG', 'LEGH',
    'LEGN', 'LEGO', 'LEGOU', 'LEGOW', 'LEJU', 'LEN', 'LEN.B', 'LEO', 'LESL',
    'LEU', 'LEVI', 'LEVL', 'LEVLP', 'LFAC', 'LFACU', 'LFACW', 'LFC', 'LFT',
    'LFTR', 'LFTRU', 'LFTRW', 'LFUS', 'LFVN', 'LGF.A', 'LGF.B', 'LGHL',
    'LGHLW', 'LGI', 'LGIH', 'LGL', 'LGL.WS', 'LGND', 'LGVW', 'LGVW.U',
    'LGVW.WS', 'LH', 'LHCG', 'LHX', 'LI', 'LIFE', 'LII', 'LILA', 'LILAK',
    'LIN', 'LINC', 'LIND', 'LINX', 'LIQT', 'LITB', 'LITE', 'LIV', 'LIVE',
    'LIVK', 'LIVKU', 'LIVKW', 'LIVN', 'LIVX', 'LIXT', 'LIXTW', 'LIZI', 'LJAQ',
    'LJAQU', 'LJAQW', 'LJPC', 'LKCO', 'LKFN', 'LKQ', 'LL', 'LLIT', 'LLNW',
    'LLY', 'LMAT', 'LMB', 'LMFA', 'LMND', 'LMNL', 'LMNR', 'LMNX', 'LMPX',
    'LMRK', 'LMRKN', 'LMRKO', 'LMRKP', 'LMST', 'LMT', 'LNC', 'LND', 'LNDC',
    'LNFA.U', 'LNG', 'LNN', 'LNSR', 'LNT', 'LNTH', 'LOAC', 'LOACR', 'LOACU',
    'LOACW', 'LOAN', 'LOB', 'LOCO', 'LODE', 'LOGC', 'LOGI', 'LOKB.U', 'LOMA',
    'LOOP', 'LOPE', 'LORL', 'LOV', 'LOVE', 'LOW', 'LPCN', 'LPG', 'LPI', 'LPL',
    'LPLA', 'LPRO', 'LPSN', 'LPTH', 'LPTX', 'LPX', 'LQDA', 'LQDT', 'LRCX',
    'LRMR', 'LRN', 'LSAQ', 'LSBK', 'LSCC', 'LSF', 'LSI', 'LSPD', 'LSTR',
    'LSXMA', 'LSXMB', 'LSXMK', 'LTBR', 'LTC', 'LTHM', 'LTRN', 'LTRPA', 'LTRPB',
    'LTRX', 'LU', 'LUB', 'LULU', 'LUMN', 'LUMO', 'LUNA', 'LUNG', 'LUV', 'LUXA',
    'LUXAU', 'LUXAW', 'LUXE', 'LVS', 'LW', 'LWAY', 'LX', 'LXEH', 'LXFR', 'LXP',
    'LXP.PRC', 'LXRX', 'LXU', 'LYB', 'LYFE', 'LYFT', 'LYG', 'LYL', 'LYRA',
    'LYTS', 'LYV', 'LZB', 'M', 'MA', 'MAA', 'MAA.PRI', 'MAAC', 'MAACU',
    'MAACW', 'MAC', 'MACK', 'MACU', 'MACUU', 'MACUW', 'MAG', 'MAGS', 'MAIN',
    'MAN', 'MANH', 'MANT', 'MANU', 'MAR', 'MARA', 'MARK', 'MARKP', 'MARPS',
    'MAS', 'MASI', 'MASS', 'MAT', 'MATW', 'MATX', 'MAV', 'MAX', 'MAXN', 'MAXR',
    'MAYS', 'MBBB', 'MBCN', 'MBI', 'MBII', 'MBIN', 'MBINO', 'MBINP', 'MBIO',
    'MBNKP', 'MBOT', 'MBRX', 'MBT', 'MBUU', 'MBWM', 'MC', 'MCA', 'MCAC',
    'MCACR', 'MCACU', 'MCB', 'MCBC', 'MCBS', 'MCD', 'MCEP', 'MCF', 'MCFE',
    'MCFT', 'MCHP', 'MCHX', 'MCI', 'MCK', 'MCMJ', 'MCMJW', 'MCN', 'MCO', 'MCR',
    'MCRB', 'MCRI', 'MCS', 'MCY', 'MD', 'MDB', 'MDC', 'MDCA', 'MDGL', 'MDGS',
    'MDGSW', 'MDIA', 'MDJH', 'MDLA', 'MDLQ', 'MDLX', 'MDLY', 'MDLZ', 'MDNA',
    'MDP', 'MDRR', 'MDRRP', 'MDRX', 'MDT', 'MDU', 'MDVL', 'MDWD', 'MDWT',
    'MDXG', 'MEC', 'MED', 'MEDP', 'MEDS', 'MEG', 'MEI', 'MEIP', 'MELI', 'MEN',
    'MEOH', 'MER.PRK', 'MERC', 'MESA', 'MESO', 'MET', 'MET.PRA', 'MET.PRE',
    'MET.PRF', 'METC', 'METX', 'METXW', 'MFA', 'MFA.PRB', 'MFA.PRC', 'MFAC',
    'MFAC.U', 'MFAC.WS', 'MFC', 'MFD', 'MFG', 'MFGP', 'MFH', 'MFIN', 'MFINL',
    'MFL', 'MFM', 'MFMS', 'MFNC', 'MFO', 'MFT', 'MFV', 'MG', 'MGA', 'MGEE',
    'MGEN', 'MGF', 'MGI', 'MGIC', 'MGLN', 'MGM', 'MGNI', 'MGNX', 'MGP', 'MGPI',
    'MGR', 'MGRB', 'MGRC', 'MGTA', 'MGTX', 'MGU', 'MGY', 'MGYR', 'MH.PRA',
    'MH.PRC', 'MH.PRD', 'MHD', 'MHE', 'MHF', 'MHH', 'MHI', 'MHK', 'MHLA',
    'MHLD', 'MHN', 'MHNC', 'MHO', 'MIC', 'MICT', 'MIDD', 'MIE', 'MIG', 'MIK',
    'MIME', 'MIN', 'MIND', 'MINDP', 'MIRM', 'MIST', 'MITK', 'MITO', 'MITT',
    'MITT.PRA', 'MITT.PRB', 'MITT.PRC', 'MIXT', 'MIY', 'MKC', 'MKC.V', 'MKD',
    'MKGI', 'MKL', 'MKSI', 'MKTX', 'MLAB', 'MLAC', 'MLACU', 'MLACW', 'MLCO',
    'MLHR', 'MLI', 'MLM', 'MLND', 'MLP', 'MLR', 'MLSS', 'MLVF', 'MMAC', 'MMC',
    'MMD', 'MMI', 'MMLP', 'MMM', 'MMP', 'MMS', 'MMSI', 'MMT', 'MMU', 'MMX',
    'MMYT', 'MN', 'MNDO', 'MNKD', 'MNOV', 'MNP', 'MNPR', 'MNR', 'MNR.PRC',
    'MNRL', 'MNRO', 'MNSB', 'MNSBP', 'MNSO', 'MNST', 'MNTX', 'MO', 'MOD',
    'MODN', 'MOFG', 'MOG.A', 'MOG.B', 'MOGO', 'MOGU', 'MOH', 'MOHO', 'MOMO',
    'MOR', 'MORF', 'MORN', 'MOS', 'MOSY', 'MOTN', 'MOTNU', 'MOTNW', 'MOTS',
    'MOTV.U', 'MOV', 'MOXC', 'MP', 'MP.WS', 'MPA', 'MPAA', 'MPB', 'MPC',
    'MPLN', 'MPLN.WS', 'MPLX', 'MPV', 'MPW', 'MPWR', 'MPX', 'MQT', 'MQY',
    'MRACU', 'MRAM', 'MRBK', 'MRC', 'MRCC', 'MRCCL', 'MRCY', 'MREO', 'MRIN',
    'MRK', 'MRKR', 'MRLN', 'MRM', 'MRNA', 'MRNS', 'MRO', 'MRSK', 'MRSN',
    'MRTN', 'MRTX', 'MRUS', 'MRVI', 'MRVL', 'MS', 'MS.PRA', 'MS.PRE', 'MS.PRF',
    'MS.PRI', 'MS.PRK', 'MS.PRL', 'MSA', 'MSB', 'MSBI', 'MSC', 'MSCI', 'MSD',
    'MSEX', 'MSFT', 'MSGE', 'MSGN', 'MSGS', 'MSI', 'MSM', 'MSN', 'MSON', 'MSP',
    'MSTB', 'MSTR', 'MSVB', 'MSVX', 'MT', 'MTA', 'MTACU', 'MTB', 'MTBC',
    'MTBCP', 'MTC', 'MTCH', 'MTCN', 'MTCR', 'MTD', 'MTDR', 'MTEM', 'MTEX',
    'MTG', 'MTH', 'MTL', 'MTL.PR', 'MTLS', 'MTN', 'MTNB', 'MTOR', 'MTP', 'MTR',
    'MTRN', 'MTRX', 'MTSC', 'MTSI', 'MTSL', 'MTT', 'MTW', 'MTX', 'MTZ', 'MU',
    'MUA', 'MUC', 'MUDSU', 'MUE', 'MUFG', 'MUH', 'MUI', 'MUJ', 'MUR', 'MUS',
    'MUSA', 'MUX', 'MVBF', 'MVF', 'MVIS', 'MVNR', 'MVO', 'MVT', 'MWA', 'MWK',
    'MX', 'MXC', 'MXE', 'MXF', 'MXIM', 'MXL', 'MYC', 'MYD', 'MYE', 'MYF',
    'MYFW', 'MYGN', 'MYI', 'MYJ', 'MYN', 'MYO', 'MYOV', 'MYRG', 'MYSZ', 'MYT',
    'MZA', 'NAC', 'NAD', 'NAII', 'NAK', 'NAKD', 'NAN', 'NAOV', 'NAPR', 'NARI',
    'NAT', 'NATH', 'NATI', 'NATR', 'NAV', 'NAV.PRD', 'NAVB', 'NAVI', 'NAZ',
    'NBA', 'NBA.U', 'NBA.WS', 'NBAC', 'NBACR', 'NBACU', 'NBACW', 'NBB', 'NBEV',
    'NBH', 'NBHC', 'NBIX', 'NBLX', 'NBN', 'NBO', 'NBR', 'NBR.PRA', 'NBRV',
    'NBSE', 'NBTB', 'NBTX', 'NBW', 'NBY', 'NC', 'NCA', 'NCB', 'NCBS', 'NCLH',
    'NCMI', 'NCNA', 'NCNO', 'NCR', 'NCSM', 'NCTY', 'NCV', 'NCV.PRA', 'NCZ',
    'NCZ.PRA', 'NDAQ', 'NDLS', 'NDMO', 'NDP', 'NDRA', 'NDRAW', 'NDSN', 'NEA',
    'NEBCU', 'NEE', 'NEE.PRK', 'NEE.PRN', 'NEE.PRO', 'NEE.PRP', 'NEE.PRQ',
    'NEM', 'NEN', 'NEO', 'NEOG', 'NEON', 'NEOS', 'NEP', 'NEPH', 'NEPT', 'NERV',
    'NES', 'NESR', 'NESRW', 'NET', 'NETE', 'NEU', 'NEV', 'NEW', 'NEWA', 'NEWR',
    'NEWT', 'NEWTI', 'NEWTL', 'NEX', 'NEXA', 'NEXT', 'NFBK', 'NFE', 'NFG',
    'NFH', 'NFH.WS', 'NFJ', 'NFLX', 'NG', 'NGA', 'NGA.U', 'NGA.WS', 'NGAC',
    'NGACU', 'NGACW', 'NGD', 'NGG', 'NGHCN', 'NGHCO', 'NGHCP', 'NGHCZ', 'NGL',
    'NGL.PRB', 'NGL.PRC', 'NGM', 'NGMS', 'NGS', 'NGVC', 'NGVT', 'NH', 'NHA',
    'NHC', 'NHF', 'NHI', 'NHIC', 'NHICU', 'NHICW', 'NHLD', 'NHLDW', 'NHS',
    'NHTC', 'NI', 'NI.PRB', 'NICE', 'NICK', 'NID', 'NIE', 'NIM', 'NINE', 'NIO',
    'NIQ', 'NISN', 'NIU', 'NJR', 'NJUL', 'NJV', 'NK', 'NKE', 'NKG', 'NKLA',
    'NKSH', 'NKTR', 'NKTX', 'NKX', 'NL', 'NLOK', 'NLS', 'NLSN', 'NLSP',
    'NLSPW', 'NLTX', 'NLY', 'NLY.PRF', 'NLY.PRG', 'NLY.PRI', 'NM', 'NM.PRG',
    'NM.PRH', 'NMCI', 'NMCO', 'NMFC', 'NMFCL', 'NMI', 'NMIH', 'NMK.PRB',
    'NMK.PRC', 'NML', 'NMM', 'NMMC', 'NMMCU', 'NMMCW', 'NMR', 'NMRD', 'NMRK',
    'NMS', 'NMT', 'NMTR', 'NMY', 'NMZ', 'NNA', 'NNBR', 'NNDM', 'NNI', 'NNN',
    'NNN.PRF', 'NNOX', 'NNVC', 'NNY', 'NOA', 'NOACU', 'NOAH', 'NOC', 'NODK',
    'NOG', 'NOK', 'NOM', 'NOMD', 'NOV', 'NOVA', 'NOVN', 'NOVS', 'NOVSU',
    'NOVSW', 'NOVT', 'NOW', 'NP', 'NPA', 'NPAUU', 'NPAWW', 'NPK', 'NPN', 'NPO',
    'NPTN', 'NPV', 'NQP', 'NR', 'NRBO', 'NRC', 'NREF', 'NREF.PRA', 'NRG',
    'NRGX', 'NRIM', 'NRIX', 'NRK', 'NRO', 'NRP', 'NRT', 'NRUC', 'NRZ',
    'NRZ.PRA', 'NRZ.PRB', 'NRZ.PRC', 'NS', 'NS.PRA', 'NS.PRB', 'NS.PRC', 'NSA',
    'NSA.PRA', 'NSC', 'NSCO', 'NSCO.WS', 'NSEC', 'NSH', 'NSH.U', 'NSH.WS',
    'NSIT', 'NSL', 'NSP', 'NSPR', 'NSPR.WS', 'NSPR.WS.B', 'NSS', 'NSSC',
    'NSTG', 'NSYS', 'NTAP', 'NTB', 'NTCO', 'NTCT', 'NTEC', 'NTES', 'NTG',
    'NTGR', 'NTIC', 'NTIP', 'NTLA', 'NTN', 'NTNX', 'NTP', 'NTR', 'NTRA',
    'NTRS', 'NTRSO', 'NTST', 'NTUS', 'NTWK', 'NTZ', 'NUAN', 'NUE', 'NUM',
    'NUO', 'NURO', 'NUS', 'NUV', 'NUVA', 'NUW', 'NUZE', 'NVAX', 'NVCN', 'NVCR',
    'NVDA', 'NVEC', 'NVEE', 'NVFY', 'NVG', 'NVGS', 'NVIV', 'NVMI', 'NVMZ',
    'NVO', 'NVR', 'NVRO', 'NVS', 'NVST', 'NVT', 'NVTA', 'NWBI', 'NWE', 'NWFL',
    'NWG', 'NWHM', 'NWL', 'NWLI', 'NWN', 'NWPX', 'NWS', 'NWSA', 'NX', 'NXC',
    'NXE', 'NXGN', 'NXJ', 'NXMD', 'NXMDW', 'NXN', 'NXP', 'NXPI', 'NXQ', 'NXR',
    'NXRT', 'NXST', 'NXTC', 'NXTD', 'NYC', 'NYCB', 'NYCB.PRA', 'NYCB.PRU',
    'NYMT', 'NYMTM', 'NYMTN', 'NYMTO', 'NYMTP', 'NYMX', 'NYT', 'NYV', 'NZF',
    'O', 'OAC', 'OAC.U', 'OAC.WS', 'OACB', 'OACB.U', 'OACB.WS', 'OAK.PRA',
    'OAK.PRB', 'OAS', 'OBAS', 'OBCI', 'OBLG', 'OBLN', 'OBNK', 'OBSV', 'OC',
    'OCA.U', 'OCC', 'OCCI', 'OCCIP', 'OCFC', 'OCFCP', 'OCFT', 'OCG', 'OCGN',
    'OCN', 'OCSI', 'OCSL', 'OCTZ', 'OCUL', 'OCUP', 'OCX', 'ODC', 'ODFL', 'ODP',
    'ODT', 'OEC', 'OEG', 'OESX', 'OFC', 'OFED', 'OFG', 'OFG.PRA', 'OFG.PRB',
    'OFG.PRD', 'OFIX', 'OFLX', 'OFS', 'OFSSG', 'OFSSI', 'OFSSL', 'OFSSZ',
    'OGE', 'OGEN', 'OGI', 'OGS', 'OHI', 'OI', 'OIA', 'OIBR.C', 'OII', 'OIIM',
    'OIS', 'OKE', 'OKTA', 'OLB', 'OLED', 'OLLI', 'OLMA', 'OLN', 'OLP', 'OM',
    'OMAB', 'OMC', 'OMCL', 'OMER', 'OMEX', 'OMF', 'OMI', 'OMP', 'ON', 'ONB',
    'ONCR', 'ONCS', 'ONCT', 'ONCY', 'ONDS', 'ONE', 'ONEM', 'ONEW', 'ONTO',
    'ONTX', 'ONTXW', 'ONVO', 'OOMA', 'OPBK', 'OPCH', 'OPEN', 'OPENW', 'OPGN',
    'OPHC', 'OPI', 'OPINI', 'OPINL', 'OPK', 'OPNT', 'OPOF', 'OPP', 'OPP.PRA',
    'OPRA', 'OPRT', 'OPRX', 'OPT', 'OPTN', 'OPTT', 'OPY', 'OR', 'ORA', 'ORAN',
    'ORBC', 'ORC', 'ORCC', 'ORCL', 'ORGO', 'ORGS', 'ORI', 'ORIC', 'ORLA',
    'ORLY', 'ORMP', 'ORN', 'ORPH', 'ORRF', 'ORTX', 'OSB', 'OSBC', 'OSG', 'OSH',
    'OSIS', 'OSK', 'OSMT', 'OSN', 'OSPN', 'OSS', 'OSTK', 'OSUR', 'OSW', 'OTEL',
    'OTEX', 'OTG', 'OTIC', 'OTIS', 'OTLK', 'OTLKW', 'OTRA', 'OTRAU', 'OTRAW',
    'OTRK', 'OTRKP', 'OTTR', 'OUT', 'OVBC', 'OVID', 'OVLY', 'OVV', 'OXBR',
    'OXBRW', 'OXFD', 'OXLC', 'OXLCM', 'OXLCO', 'OXLCP', 'OXM', 'OXSQ', 'OXSQL',
    'OXSQZ', 'OXY', 'OXY.WS', 'OYST', 'OZK', 'OZON', 'PAA', 'PAAS', 'PAC',
    'PACB', 'PACE', 'PACE.U', 'PACE.WS', 'PACK', 'PACW', 'PAE', 'PAEWW', 'PAG',
    'PAGP', 'PAGS', 'PAHC', 'PAI', 'PAIC', 'PAICU', 'PAICW', 'PAM', 'PANA',
    'PANA.U', 'PANA.WS', 'PAND', 'PANL', 'PANW', 'PAR', 'PARR', 'PASG', 'PATI',
    'PATK', 'PAVM', 'PAVMW', 'PAVMZ', 'PAYA', 'PAYAW', 'PAYC', 'PAYS', 'PAYX',
    'PB', 'PBA', 'PBB', 'PBC', 'PBCT', 'PBCTP', 'PBF', 'PBFS', 'PBFX', 'PBH',
    'PBHC', 'PBI', 'PBI.PRB', 'PBIO', 'PBIP', 'PBLA', 'PBPB', 'PBR', 'PBR.A',
    'PBT', 'PBTS', 'PBY', 'PBYI', 'PCAR', 'PCB', 'PCF', 'PCG', 'PCG.PRA',
    'PCG.PRB', 'PCG.PRC', 'PCG.PRD', 'PCG.PRE', 'PCG.PRG', 'PCG.PRH',
    'PCG.PRI', 'PCGU', 'PCH', 'PCI', 'PCIM', 'PCK', 'PCM', 'PCN', 'PCOM',
    'PCPC.U', 'PCPL', 'PCPL.U', 'PCPL.WS', 'PCQ', 'PCRX', 'PCSA', 'PCSB',
    'PCTI', 'PCTY', 'PCVX', 'PCYG', 'PCYO', 'PD', 'PDAC', 'PDAC.U', 'PDAC.WS',
    'PDCE', 'PDCO', 'PDD', 'PDEX', 'PDFS', 'PDI', 'PDLB', 'PDM', 'PDS', 'PDSB',
    'PDT', 'PE', 'PEAK', 'PEB', 'PEB.PRC', 'PEB.PRD', 'PEB.PRE', 'PEB.PRF',
    'PEBK', 'PEBO', 'PECK', 'PED', 'PEG', 'PEGA', 'PEI', 'PEI.PRB', 'PEI.PRC',
    'PEI.PRD', 'PEIX', 'PEN', 'PENN', 'PEO', 'PEP', 'PERI', 'PESI', 'PETQ',
    'PETS', 'PETZ', 'PFBC', 'PFBI', 'PFC', 'PFD', 'PFE', 'PFG', 'PFGC', 'PFH',
    'PFHD', 'PFIE', 'PFIN', 'PFIS', 'PFL', 'PFLT', 'PFMT', 'PFN', 'PFO',
    'PFPT', 'PFS', 'PFSI', 'PFSW', 'PFX', 'PFXNL', 'PG', 'PGC', 'PGEN', 'PGNY',
    'PGP', 'PGR', 'PGRE', 'PGTI', 'PGZ', 'PH', 'PHAR', 'PHAS', 'PHAT', 'PHCF',
    'PHD', 'PHG', 'PHGE', 'PHGE.U', 'PHGE.WS', 'PHI', 'PHICU', 'PHIO', 'PHIOW',
    'PHK', 'PHM', 'PHR', 'PHT', 'PHUN', 'PHUNW', 'PHX', 'PI', 'PIAI', 'PIAI.U',
    'PIAI.WS', 'PICO', 'PII', 'PIM', 'PINC', 'PINE', 'PING', 'PINS', 'PIPP.U',
    'PIPR', 'PIRS', 'PIXY', 'PJT', 'PK', 'PKBK', 'PKE', 'PKG', 'PKI', 'PKO',
    'PKOH', 'PKX', 'PLAB', 'PLAG', 'PLAN', 'PLAY', 'PLBC', 'PLCE', 'PLD',
    'PLG', 'PLIN', 'PLL', 'PLM', 'PLMR', 'PLNT', 'PLOW', 'PLPC', 'PLRX',
    'PLSE', 'PLT', 'PLTR', 'PLUG', 'PLUS', 'PLX', 'PLXP', 'PLXS', 'PLYA',
    'PLYM', 'PLYM.PRA', 'PM', 'PMAR', 'PMBC', 'PMD', 'PME', 'PMF', 'PML',
    'PMM', 'PMO', 'PMT', 'PMT.PRA', 'PMT.PRB', 'PMVC', 'PMVC.U', 'PMVC.WS',
    'PMVP', 'PMX', 'PNBK', 'PNC', 'PNC.PRP', 'PNF', 'PNFP', 'PNFPP', 'PNI',
    'PNM', 'PNNT', 'PNNTG', 'PNR', 'PNRG', 'PNTG', 'PNW', 'POAI', 'PODD',
    'POLA', 'POOL', 'POR', 'POST', 'POWI', 'POWL', 'POWW', 'PPBI', 'PPBT',
    'PPC', 'PPD', 'PPG', 'PPGH', 'PPGHU', 'PPGHW', 'PPIH', 'PPL', 'PPR',
    'PPSI', 'PPT', 'PPX', 'PQG', 'PRA', 'PRAA', 'PRAH', 'PRAX', 'PRCH',
    'PRCHW', 'PRDO', 'PRE.PRG', 'PRE.PRH', 'PRE.PRI', 'PRFT', 'PRFX', 'PRG',
    'PRGO', 'PRGS', 'PRGX', 'PRI', 'PRIF.PRA', 'PRIF.PRB', 'PRIF.PRC',
    'PRIF.PRD', 'PRIF.PRE', 'PRIF.PRF', 'PRIM', 'PRK', 'PRLB', 'PRLD', 'PRMW',
    'PRO', 'PROF', 'PROG', 'PROS', 'PROV', 'PRPB', 'PRPB.U', 'PRPB.WS', 'PRPH',
    'PRPL', 'PRPO', 'PRQR', 'PRS', 'PRSC', 'PRSP', 'PRT', 'PRTA', 'PRTC',
    'PRTH', 'PRTK', 'PRTS', 'PRTY', 'PRU', 'PRVB', 'PRVL', 'PS', 'PSA',
    'PSA.PRB', 'PSA.PRC', 'PSA.PRD', 'PSA.PRE', 'PSA.PRF', 'PSA.PRG',
    'PSA.PRH', 'PSA.PRI', 'PSA.PRJ', 'PSA.PRK', 'PSA.PRL', 'PSA.PRM',
    'PSA.PRN', 'PSA.PRO', 'PSAC', 'PSACU', 'PSACW', 'PSB', 'PSB.PRW',
    'PSB.PRX', 'PSB.PRY', 'PSB.PRZ', 'PSCX', 'PSEC', 'PSF', 'PSFD', 'PSFF',
    'PSHG', 'PSMD', 'PSMT', 'PSN', 'PSNL', 'PSO', 'PSTG', 'PSTH', 'PSTH.WS',
    'PSTI', 'PSTL', 'PSTV', 'PSTX', 'PSX', 'PSXP', 'PT', 'PTA', 'PTC', 'PTCT',
    'PTE', 'PTEN', 'PTGX', 'PTICU', 'PTK', 'PTK.U', 'PTK.WS', 'PTMN', 'PTN',
    'PTNR', 'PTON', 'PTPI', 'PTR', 'PTRS', 'PTSI', 'PTVCA', 'PTVCB', 'PTVE',
    'PTY', 'PUBM', 'PUK', 'PUK.PR', 'PUK.PRA', 'PULM', 'PUMP', 'PUYI', 'PVAC',
    'PVBC', 'PVG', 'PVH', 'PVL', 'PW', 'PW.PRA', 'PWFL', 'PWOD', 'PWR', 'PXD',
    'PXLW', 'PXMD', 'PXS', 'PXSAP', 'PXSAW', 'PYN', 'PYPD', 'PYPL', 'PYS',
    'PYT', 'PZC', 'PZG', 'PZN', 'PZZA', 'QADA', 'QADB', 'QCOM', 'QCRH', 'QD',
    'QDEC', 'QDEL', 'QELL', 'QELLU', 'QELLW', 'QEP', 'QFIN', 'QGEN', 'QH',
    'QIWI', 'QK', 'QLGN', 'QLYS', 'QMCO', 'QNST', 'QQQX', 'QRHC', 'QRTEA',
    'QRTEB', 'QRTEP', 'QRVO', 'QS', 'QS.WS', 'QSR', 'QTNT', 'QTRX', 'QTS',
    'QTS.PRA', 'QTS.PRB', 'QTT', 'QTWO', 'QUAD', 'QUIK', 'QUMU', 'QUOT',
    'QURE', 'QVCC', 'QVCD', 'R', 'RA', 'RAACU', 'RACA', 'RACE', 'RAD', 'RADA',
    'RADI', 'RAIL', 'RAMP', 'RAND', 'RAPT', 'RARE', 'RAVE', 'RAVN', 'RBA',
    'RBAC', 'RBAC.U', 'RBAC.WS', 'RBB', 'RBBN', 'RBC', 'RBCAA', 'RBCN', 'RBKB',
    'RBNC', 'RC', 'RCA', 'RCB', 'RCEL', 'RCG', 'RCHG', 'RCHGU', 'RCHGW', 'RCI',
    'RCII', 'RCKT', 'RCKY', 'RCL', 'RCM', 'RCMT', 'RCON', 'RCP', 'RCS', 'RCUS',
    'RDCM', 'RDFI', 'RDFN', 'RDHL', 'RDI', 'RDIB', 'RDN', 'RDNT', 'RDS.A',
    'RDS/B', 'RDUS', 'RDVT', 'RDWR', 'RDY', 'RE', 'REAL', 'REC', 'REDU',
    'REED', 'REFR', 'REG', 'REGI', 'REGN', 'REI', 'REKR', 'RELL', 'RELX',
    'RENN', 'REPH', 'REPL', 'RES', 'RESI', 'RESN', 'RETA', 'RETO', 'REV',
    'REVG', 'REX', 'REXR', 'REXR.PRA', 'REXR.PRB', 'REXR.PRC', 'REYN', 'REZI',
    'RF', 'RF.PRA', 'RF.PRB', 'RF.PRC', 'RFI', 'RFIL', 'RFL', 'RFM', 'RFP',
    'RGA', 'RGCO', 'RGEN', 'RGLD', 'RGLS', 'RGNX', 'RGP', 'RGR', 'RGS', 'RGT',
    'RH', 'RHE', 'RHE.PRA', 'RHI', 'RHP', 'RIBT', 'RICE', 'RICE.U', 'RICE.WS',
    'RICK', 'RIDE', 'RIDEW', 'RIG', 'RIGL', 'RILY', 'RILYG', 'RILYH', 'RILYI',
    'RILYL', 'RILYM', 'RILYN', 'RILYO', 'RILYP', 'RILYZ', 'RIO', 'RIOT', 'RIV',
    'RIVE', 'RJF', 'RKDA', 'RKT', 'RL', 'RLAY', 'RLGT', 'RLGY', 'RLH', 'RLI',
    'RLJ', 'RLJ.PRA', 'RLMD', 'RM', 'RMAX', 'RMBI', 'RMBL', 'RMBS', 'RMCF',
    'RMD', 'RMED', 'RMGBU', 'RMI', 'RMM', 'RMNI', 'RMO', 'RMO.WS', 'RMPL.PR',
    'RMR', 'RMRM', 'RMT', 'RMTI', 'RNA', 'RNDB', 'RNET', 'RNG', 'RNGR', 'RNLX',
    'RNP', 'RNR', 'RNR.PRE', 'RNR.PRF', 'RNST', 'RNWK', 'ROAD', 'ROCC',
    'ROCCU', 'ROCCW', 'ROCH', 'ROCHU', 'ROCHW', 'ROCK', 'ROG', 'ROIC', 'ROK',
    'ROKU', 'ROL', 'ROLL', 'ROMO', 'ROOT', 'ROP', 'ROST', 'RP', 'RPAI', 'RPAY',
    'RPD', 'RPLA', 'RPLA.U', 'RPLA.WS', 'RPM', 'RPRX', 'RPT', 'RPT.PRD',
    'RPTX', 'RQI', 'RRBI', 'RRC', 'RRD', 'RRGB', 'RRR', 'RS', 'RSF', 'RSG',
    'RSI', 'RSI.WS', 'RSSS', 'RSVA', 'RSVAU', 'RSVAW', 'RTAI', 'RTLR', 'RTP',
    'RTP.U', 'RTP.WS', 'RTPZ.U', 'RTX', 'RUBY', 'RUHN', 'RUN', 'RUSHA',
    'RUSHB', 'RUTH', 'RVI', 'RVLV', 'RVMD', 'RVNC', 'RVP', 'RVPH', 'RVPHW',
    'RVSB', 'RVT', 'RWLK', 'RWT', 'RXN', 'RXT', 'RY', 'RY.PRT', 'RYAAY',
    'RYAM', 'RYB', 'RYI', 'RYN', 'RYTM', 'RZA', 'RZB', 'RZLT', 'SA', 'SABR',
    'SABRP', 'SACC', 'SACH', 'SAF', 'SAFE', 'SAFM', 'SAFT', 'SAGE', 'SAH',
    'SAIA', 'SAIC', 'SAII', 'SAIIU', 'SAIIW', 'SAIL', 'SAK', 'SAL', 'SALM',
    'SALT', 'SAM', 'SAMG', 'SAN', 'SAND          ', 'SANM', 'SANW', 'SAP',
    'SAR', 'SASR', 'SATS', 'SAVA', 'SAVE', 'SB', 'SB.PRC', 'SB.PRD', 'SBAC',
    'SBBA', 'SBBP', 'SBCF', 'SBE', 'SBE.U', 'SBE.WS', 'SBFG', 'SBG', 'SBG.U',
    'SBG.WS', 'SBGI', 'SBH', 'SBI', 'SBLK', 'SBLKZ', 'SBNY', 'SBNYP', 'SBOW',
    'SBR', 'SBRA', 'SBS', 'SBSI', 'SBSW', 'SBT', 'SBTX', 'SBUX', 'SC', 'SCA',
    'SCCB', 'SCCC', 'SCCI', 'SCCO', 'SCD', 'SCE.PRG', 'SCE.PRH', 'SCE.PRJ',
    'SCE.PRK', 'SCE.PRL', 'SCHL', 'SCHN', 'SCHW', 'SCHW.PRC', 'SCHW.PRD',
    'SCI', 'SCKT', 'SCL', 'SCM', 'SCOAU', 'SCOR', 'SCPE', 'SCPE.U', 'SCPE.WS',
    'SCPH', 'SCPL', 'SCPS', 'SCS', 'SCSC', 'SCU', 'SCVL', 'SCVX', 'SCVX.U',
    'SCVX.WS', 'SCWX', 'SCX', 'SCYX', 'SD', 'SDC', 'SDGR', 'SDHY', 'SDPI',
    'SE', 'SEAC', 'SEAH', 'SEAH.U', 'SEAH.WS', 'SEAS', 'SEB', 'SECO', 'SEDG',
    'SEE', 'SEED', 'SEEL', 'SEER', 'SEIC', 'SELB', 'SELF', 'SEM', 'SENEA',
    'SENEB', 'SENS', 'SEPZ', 'SESN', 'SF', 'SF.PRA', 'SF.PRB', 'SF.PRC', 'SFB',
    'SFBC', 'SFBS', 'SFE', 'SFET', 'SFIX', 'SFL', 'SFM', 'SFNC', 'SFST', 'SFT',
    'SFTTW', 'SFTW', 'SFTW.U', 'SFTW.WS', 'SFUN', 'SG', 'SGA', 'SGAM', 'SGAMU',
    'SGAMW', 'SGBX', 'SGC', 'SGEN', 'SGH', 'SGLB', 'SGLBW', 'SGMA', 'SGMO',
    'SGMS', 'SGOC', 'SGRP', 'SGRY', 'SGTX', 'SGU', 'SHAK', 'SHBI', 'SHC',
    'SHEN', 'SHG', 'SHI', 'SHIP', 'SHIPW', 'SHIPZ', 'SHLX', 'SHO', 'SHO.PRE',
    'SHO.PRF', 'SHOO', 'SHOP', 'SHSP', 'SHW', 'SHYF', 'SI', 'SIBN', 'SIC',
    'SID', 'SIEB', 'SIEN', 'SIF', 'SIFY', 'SIG', 'SIGA', 'SIGI', 'SIGIP',
    'SII', 'SILC', 'SILK', 'SILV', 'SIM', 'SIMO', 'SINA', 'SINO', 'SINT',
    'SIOX', 'SIRI', 'SITC', 'SITC.PRA', 'SITC.PRK', 'SITE', 'SITM', 'SIVB',
    'SIVBP', 'SIX', 'SJ', 'SJI', 'SJIJ', 'SJIU', 'SJM', 'SJR', 'SJT', 'SJW',
    'SKLZ', 'SKLZ.WS', 'SKM', 'SKT', 'SKX', 'SKY', 'SKYW', 'SLAB', 'SLB',
    'SLCA', 'SLCT', 'SLDB', 'SLF', 'SLG', 'SLG.PRI', 'SLGG', 'SLGL', 'SLGN',
    'SLM', 'SLMBP', 'SLN', 'SLNO', 'SLP', 'SLQT', 'SLRC', 'SLRX', 'SLS', 'SM',
    'SMAR', 'SMBC', 'SMBK', 'SMCI', 'SMED', 'SMFG', 'SMG', 'SMHI', 'SMID',
    'SMIT', 'SMLP', 'SMM', 'SMMC', 'SMMCU', 'SMMCW', 'SMMF', 'SMMT', 'SMP',
    'SMPL', 'SMSI', 'SMTC', 'SMTI', 'SMTS', 'SMTX', 'SNA', 'SNAP', 'SNBR',
    'SNCA', 'SNCR', 'SND', 'SNDE', 'SNDL', 'SNDR', 'SNDX', 'SNE', 'SNES',
    'SNEX', 'SNFCA', 'SNGX', 'SNGXW', 'SNMP', 'SNN', 'SNOA', 'SNOW', 'SNP',
    'SNPR', 'SNPR.U', 'SNPR.WS', 'SNPS', 'SNR', 'SNRHU', 'SNSS', 'SNV',
    'SNV.PRD', 'SNV.PRE', 'SNX', 'SNY', 'SO', 'SOAC', 'SOAC.U', 'SOAC.WS',
    'SOGO', 'SOHO', 'SOHOB', 'SOHON', 'SOHOO', 'SOHU', 'SOI', 'SOJB', 'SOJC',
    'SOJD', 'SOJE', 'SOL', 'SOLN', 'SOLO', 'SOLOW', 'SOLY', 'SON', 'SONA',
    'SONM', 'SONN', 'SONO', 'SOR', 'SOS', 'SP', 'SPB', 'SPCB', 'SPCE', 'SPE',
    'SPE.PRB', 'SPEL', 'SPFI', 'SPFR.U', 'SPG', 'SPG.PRJ', 'SPGI', 'SPH',
    'SPI', 'SPKE', 'SPKEP', 'SPLK', 'SPLP', 'SPLP.PRA', 'SPNE', 'SPNS', 'SPNV',
    'SPNV.U', 'SPNV.WS', 'SPOK', 'SPOT', 'SPPI', 'SPR', 'SPRB', 'SPRO',
    'SPRQ.U', 'SPRT', 'SPSC', 'SPT', 'SPTN', 'SPWH', 'SPWR', 'SPXC', 'SPXX',
    'SQ', 'SQBG', 'SQFT', 'SQM', 'SQNS', 'SQZ', 'SR', 'SR.PRA', 'SRAC',
    'SRACU', 'SRACW', 'SRAX', 'SRC', 'SRC.PRA', 'SRCE', 'SRCL', 'SRDX', 'SRE',
    'SRE.PRA', 'SRE.PRB', 'SREA', 'SREV', 'SRG', 'SRG.PRA', 'SRGA', 'SRI',
    'SRL', 'SRLP', 'SRNE', 'SRPT', 'SRRA', 'SRRK', 'SRSA', 'SRSAU', 'SRSAW',
    'SRT', 'SRTS', 'SRV', 'SRVA', 'SSB', 'SSBI', 'SSD', 'SSKN', 'SSL', 'SSNC',
    'SSNT', 'SSP', 'SSPK', 'SSPKU', 'SSPKW', 'SSRM', 'SSSS', 'SSTI', 'SSTK',
    'SSY', 'SSYS', 'ST', 'STAA', 'STAF', 'STAG', 'STAG.PRC', 'STAR          ',
    'STAR.PRD', 'STAR.PRG', 'STAR.PRI', 'STAY', 'STBA', 'STC', 'STCN', 'STE',
    'STEP', 'STFC', 'STG', 'STIC', 'STIC.U', 'STIC.WS', 'STIM', 'STK', 'STKL',
    'STKS', 'STL', 'STL.PRA', 'STLD', 'STM', 'STMP', 'STN', 'STND', 'STNE',
    'STNG', 'STOK', 'STON', 'STOR', 'STPK', 'STPK.U', 'STPK.WS', 'STRA',
    'STRL', 'STRM', 'STRO', 'STRR', 'STRRP', 'STRS', 'STRT', 'STSA', 'STT',
    'STT.PRD', 'STT.PRG', 'STTK', 'STWD', 'STWO', 'STWOU', 'STWOW', 'STX',
    'STXB', 'STXS', 'STZ', 'STZ/B', 'SU', 'SUI', 'SULR', 'SUM', 'SUMO', 'SUMR',
    'SUN', 'SUNS', 'SUNW', 'SUP', 'SUPN', 'SUPV', 'SURF', 'SUZ', 'SV', 'SVA',
    'SVAC', 'SVACU', 'SVACW', 'SVAL', 'SVBI', 'SVC', 'SVM', 'SVMK', 'SVOKU',
    'SVRA', 'SVSVU', 'SVSVW', 'SVT', 'SVVC', 'SWAV', 'SWBI', 'SWCH', 'SWI',
    'SWIR', 'SWK', 'SWKH', 'SWKS', 'SWM', 'SWN', 'SWT', 'SWTX', 'SWX', 'SWZ',
    'SXC', 'SXI', 'SXT', 'SXTC', 'SY', 'SYBT', 'SYBX', 'SYF', 'SYF.PRA', 'SYK',
    'SYKE', 'SYN', 'SYNA', 'SYNC', 'SYNH', 'SYNL', 'SYPR', 'SYRS', 'SYTA',
    'SYTAW', 'SYX', 'SYY', 'SZC', 'T', 'T.PRA', 'T.PRC', 'TA', 'TAC', 'TACA.U',
    'TACO', 'TACT', 'TAEQ', 'TAIT', 'TAK', 'TAL', 'TALO', 'TALO.WS', 'TANH',
    'TANNI', 'TANNL', 'TANNZ', 'TAOP', 'TAP', 'TAP.A', 'TARA', 'TARO', 'TARS',
    'TAST', 'TATT', 'TAYD', 'TBB', 'TBBK', 'TBC', 'TBI', 'TBIO', 'TBJL', 'TBK',
    'TBKCP', 'TBLT', 'TBLTW', 'TBNK', 'TBPH', 'TC', 'TCBI', 'TCBIL', 'TCBIP',
    'TCBK', 'TCCO', 'TCDA', 'TCF', 'TCFC', 'TCFCP', 'TCI', 'TCMD', 'TCOM',
    'TCON', 'TCP', 'TCPC', 'TCRR', 'TCS', 'TCX', 'TD', 'TDA', 'TDAC', 'TDACU',
    'TDACW', 'TDC', 'TDE', 'TDF', 'TDG', 'TDI', 'TDJ', 'TDOC', 'TDS', 'TDW',
    'TDW.WS', 'TDW.WS.A', 'TDW.WS.B', 'TDY', 'TEAF', 'TEAM', 'TECH', 'TECK',
    'TECTP', 'TEDU', 'TEF', 'TEGS', 'TEI', 'TEKK', 'TEKKU', 'TEKKW', 'TEL',
    'TELA', 'TELL', 'TEN', 'TENB', 'TENX', 'TEO', 'TER', 'TESS', 'TEVA', 'TEX',
    'TFC', 'TFC.PRF', 'TFC.PRG', 'TFC.PRH', 'TFC.PRI', 'TFC.PRO', 'TFC.PRR',
    'TFFP', 'TFII', 'TFJL', 'TFSL', 'TFX', 'TG', 'TGA', 'TGB', 'TGC', 'TGH',
    'TGI', 'TGLS', 'TGNA', 'TGP', 'TGP.PRA', 'TGP.PRB', 'TGS', 'TGT', 'TGTX',
    'TH', 'THBR', 'THBRU', 'THBRW', 'THC', 'THCA', 'THCAU', 'THCAW', 'THCB',
    'THCBU', 'THCBW', 'THFF', 'THG', 'THM', 'THMO', 'THO', 'THQ', 'THR', 'THRM',
    'THRY', 'THS', 'THTX', 'THW', 'THWWW', 'THY', 'TIF', 'TIG', 'TIGO', 'TIGR',
    'TILE', 'TIMB', 'TINV.U', 'TIPT', 'TISI', 'TITN', 'TJX', 'TK', 'TKAT',
    'TKC', 'TKR', 'TLC', 'TLGT', 'TLK', 'TLMD', 'TLMDW', 'TLND', 'TLRY', 'TLS',
    'TLSA', 'TLYS', 'TM', 'TMBR', 'TMDI', 'TMDX', 'TME', 'TMHC', 'TMO', 'TMP',
    'TMPM', 'TMPMU', 'TMPMW', 'TMQ', 'TMST', 'TMTS', 'TMTSU', 'TMTSW', 'TMUS',
    'TMX', 'TNAV', 'TNC', 'TNDM', 'TNET', 'TNK', 'TNP', 'TNP.PRD', 'TNP.PRE',
    'TNP.PRF', 'TNXP', 'TOL', 'TOMZ', 'TOPS', 'TOT', 'TOUR', 'TOWN', 'TPB',
    'TPC', 'TPCO', 'TPGY', 'TPGY.U', 'TPGY.WS', 'TPH', 'TPHS', 'TPIC', 'TPL',
    'TPR', 'TPRE', 'TPTX', 'TPVG', 'TPVY', 'TPX', 'TPZ', 'TR', 'TRC', 'TRCH',
    'TREB', 'TREB.U', 'TREB.WS', 'TREC', 'TREE', 'TREX', 'TRGP', 'TRHC', 'TRI',
    'TRIB', 'TRIL', 'TRIP', 'TRIT', 'TRITW', 'TRMB', 'TRMD', 'TRMK', 'TRMT',
    'TRN', 'TRNO', 'TRNS', 'TROW', 'TROX', 'TRP', 'TRQ', 'TRS', 'TRST', 'TRT',
    'TRTN', 'TRTN.PRA', 'TRTN.PRB', 'TRTN.PRC', 'TRTN.PRD', 'TRTX', 'TRU',
    'TRUE', 'TRUP', 'TRV', 'TRVG', 'TRVI', 'TRVN', 'TRX', 'TRXC', 'TS', 'TSBK',
    'TSC', 'TSCAP', 'TSCBP', 'TSCO', 'TSE', 'TSEM', 'TSHA', 'TSI', 'TSIA',
    'TSIAU', 'TSIAW', 'TSJA', 'TSLA', 'TSLX', 'TSM', 'TSN', 'TSOC', 'TSQ',
    'TSRI', 'TT', 'TTC', 'TTCF', 'TTCFW', 'TTD', 'TTEC', 'TTEK', 'TTGT', 'TTI',
    'TTM', 'TTMI', 'TTNP', 'TTOO', 'TTP', 'TTWO', 'TU', 'TUFN', 'TUP', 'TURN',
    'TUSK', 'TV', 'TVACU', 'TVC', 'TVE', 'TVTX', 'TVTY', 'TW', 'TWCT', 'TWCTU',
    'TWCTW', 'TWI', 'TWIN', 'TWLO', 'TWN', 'TWND', 'TWND.U', 'TWND.WS', 'TWNK',
    'TWNKW', 'TWO', 'TWO.PRA', 'TWO.PRB', 'TWO.PRC', 'TWO.PRD', 'TWO.PRE',
    'TWOU', 'TWST', 'TWTR', 'TX', 'TXG', 'TXMD', 'TXN', 'TXRH', 'TXT', 'TY',
    'TY.PR', 'TYG', 'TYHT', 'TYL', 'TYME', 'TZOO', 'U', 'UA', 'UAA', 'UAL',
    'UAMY', 'UAN', 'UAVS', 'UBA', 'UBCP', 'UBER', 'UBFO', 'UBOH', 'UBP',
    'UBP.PRH', 'UBP.PRK', 'UBS', 'UBSI', 'UBX', 'UCBI', 'UCBIO', 'UCL', 'UCTT',
    'UDR', 'UE', 'UEC', 'UEIC', 'UEPS', 'UFAB', 'UFCS', 'UFI', 'UFPI', 'UFPT',
    'UFS', 'UG', 'UGI', 'UGP', 'UHAL', 'UHS', 'UHT', 'UI', 'UIHC', 'UIS', 'UK',
    'UKOMW', 'UL', 'ULBI', 'ULH', 'ULTA', 'UMAR', 'UMBF', 'UMC', 'UMH',
    'UMH.PRC', 'UMH.PRD', 'UMPQ', 'UNAM', 'UNB', 'UNF', 'UNFI', 'UNH', 'UNIT',
    'UNM', 'UNMA', 'UNP', 'UNTY', 'UNVR', 'UONE', 'UONEK', 'UPLD', 'UPS',
    'UPST', 'UPWK', 'URBN', 'URG', 'URGN', 'URI', 'UROV', 'USA', 'USAC',
    'USAK', 'USAP', 'USAS', 'USAT', 'USAU', 'USB', 'USB.PRA', 'USB.PRH',
    'USB.PRM', 'USB.PRO', 'USB.PRP', 'USB.PRQ', 'USCR', 'USDP', 'USEG', 'USFD',
    'USIO', 'USLM', 'USM', 'USNA', 'USPH', 'USWS', 'USWSW', 'USX', 'UTF',
    'UTG', 'UTHR', 'UTI', 'UTL', 'UTMD', 'UTSI', 'UTZ', 'UTZ.WS', 'UUU',
    'UUUU', 'UUUU.WS', 'UVE', 'UVSP', 'UVV', 'UXIN', 'UZA', 'UZB', 'UZC',
    'UZD', 'UZE', 'V', 'VAC', 'VACQ', 'VACQU', 'VACQW', 'VALE', 'VALU', 'VAPO',
    'VAR', 'VBF', 'VBFC', 'VBIV', 'VBLT', 'VBTX', 'VC', 'VCEL', 'VCF', 'VCIF',
    'VCNX', 'VCRA', 'VCTR', 'VCV', 'VCVCU', 'VCYT', 'VEC', 'VECO', 'VEDL',
    'VEEV', 'VEL', 'VEON', 'VER', 'VER.PRF', 'VERB', 'VERBW', 'VERI', 'VERO',
    'VERT.U', 'VERU', 'VERX', 'VERY', 'VET', 'VFC', 'VFF', 'VFL', 'VG', 'VGAC',
    'VGAC.U', 'VGAC.WS', 'VGI', 'VGM', 'VGR', 'VGZ', 'VHAQ.U', 'VHC', 'VHI',
    'VIAC', 'VIACA', 'VIAO', 'VIAV', 'VICI', 'VICR', 'VIE', 'VIH', 'VIHAU',
    'VIHAW', 'VIIAU', 'VINC', 'VINCU', 'VINCW', 'VIOT', 'VIPS', 'VIR', 'VIRC',
    'VIRI', 'VIRS', 'VIRT', 'VISL', 'VIST', 'VITL', 'VIV', 'VIVE', 'VIVO',
    'VJET', 'VKI', 'VKQ', 'VKTX', 'VKTXW', 'VLDR', 'VLDRW', 'VLGEA', 'VLO',
    'VLRS', 'VLT', 'VLY', 'VLYPO', 'VLYPP', 'VMAC', 'VMACU', 'VMACW', 'VMAR',
    'VMC', 'VMD', 'VMI', 'VMM', 'VMO', 'VMW', 'VNCE', 'VNDA', 'VNE', 'VNET',
    'VNO', 'VNO.PRK', 'VNO.PRL', 'VNO.PRM', 'VNO.PRN', 'VNOM', 'VNRX', 'VNT',
    'VNTR', 'VOC', 'VOD', 'VOLT', 'VOXX', 'VOYA', 'VOYA.PRB', 'VPG', 'VPV',
    'VRA', 'VRAY', 'VRCA', 'VREX', 'VRM', 'VRME', 'VRMEW', 'VRNA', 'VRNS',
    'VRNT', 'VRRM', 'VRS', 'VRSK', 'VRSN', 'VRT', 'VRT.WS', 'VRTS', 'VRTU',
    'VRTV', 'VRTX', 'VS', 'VSAT', 'VSEC', 'VSH', 'VSPR', 'VSPRU', 'VSPRW',
    'VSSYW', 'VST', 'VST.WS.A', 'VSTA', 'VSTM', 'VSTO', 'VTA', 'VTAQU', 'VTEC',
    'VTGN', 'VTIQ', 'VTIQU', 'VTIQW', 'VTN', 'VTNR', 'VTOL', 'VTR', 'VTRS',
    'VTRU', 'VTSI', 'VTVT', 'VUZI', 'VVI', 'VVNT', 'VVNT.WS', 'VVOS', 'VVPR',
    'VVR', 'VVV', 'VXRT', 'VYGG', 'VYGG.U', 'VYGG.WS', 'VYGR', 'VYNE', 'VZ',
    'W', 'WAB', 'WABC', 'WAFD', 'WAFU', 'WAL', 'WALA', 'WASH', 'WAT', 'WATT',
    'WB', 'WBA', 'WBAI', 'WBK', 'WBS', 'WBS.PRF', 'WBT', 'WCC', 'WCC.PRA',
    'WCN', 'WD', 'WDAY', 'WDC', 'WDFC', 'WDR', 'WEA', 'WEC', 'WEI', 'WELL',
    'WEN', 'WERN', 'WES', 'WETF', 'WEX', 'WEYS', 'WF', 'WFC', 'WFC.PRA',
    'WFC.PRL', 'WFC.PRN', 'WFC.PRO', 'WFC.PRP', 'WFC.PRQ', 'WFC.PRR',
    'WFC.PRW', 'WFC.PRX', 'WFC.PRY', 'WFC.PRZ', 'WGO', 'WH', 'WHD', 'WHF',
    'WHFBZ', 'WHG', 'WHLM', 'WHLR', 'WHLRD', 'WHLRP', 'WHR', 'WIA', 'WIFI',
    'WILC', 'WIMI', 'WINA', 'WING', 'WINT', 'WIRE', 'WISA', 'WISH', 'WIT',
    'WIW', 'WIX', 'WK', 'WKEY', 'WKHS', 'WLDN', 'WLFC', 'WLK', 'WLKP', 'WLL',
    'WLTW', 'WM', 'WMB', 'WMC', 'WMG', 'WMK', 'WMS', 'WMT', 'WNC', 'WNEB',
    'WNFM', 'WNS', 'WNW', 'WOR', 'WORK', 'WORX', 'WOW', 'WPC', 'WPF', 'WPF.U',
    'WPF.WS', 'WPG', 'WPG.PRH', 'WPG.PRI', 'WPM', 'WPP', 'WPRT', 'WPX', 'WRAP',
    'WRB', 'WRB.PRC', 'WRB.PRD', 'WRB.PRE', 'WRB.PRF', 'WRB.PRG', 'WRE', 'WRI',
    'WRK', 'WRLD', 'WRN', 'WSBC', 'WSBCP', 'WSBF', 'WSC', 'WSFS', 'WSG', 'WSM',
    'WSO', 'WSO/B', 'WSR', 'WST', 'WSTG', 'WTBA', 'WTER', 'WTFC', 'WTFCM',
    'WTFCP', 'WTI', 'WTM', 'WTRE', 'WTREP', 'WTRG', 'WTRH', 'WTRU', 'WTS',
    'WTT', 'WTTR', 'WU', 'WUGI', 'WVE', 'WVFC', 'WVVI', 'WVVIP', 'WW', 'WWD',
    'WWE', 'WWR', 'WWW', 'WY', 'WYND', 'WYNN', 'WYY', 'X', 'XAIR', 'XAN',
    'XAN.PRC', 'XBIO', 'XBIOW', 'XBIT', 'XCUR', 'XEC', 'XEL', 'XELA', 'XELB',
    'XENE', 'XENT', 'XERS', 'XFLT', 'XFOR', 'XGN', 'XHR', 'XIN', 'XJH', 'XJR',
    'XL', 'XL.WS', 'XLNX', 'XLRN', 'XNCR', 'XNET', 'XOM', 'XOMA', 'XOMAP',
    'XONE', 'XP', 'XPEL', 'XPER', 'XPEV', 'XPL', 'XPO', 'XPOA', 'XPOA.U',
    'XPOA.WS', 'XRAY', 'XRX', 'XSPA', 'XTLB', 'XTNT', 'XVV', 'XXII', 'XYF',
    'XYL', 'Y', 'YAC', 'YAC.U', 'YAC.WS', 'YALA', 'YCBD', 'YCBD.PRA', 'YDEC',
    'YELP', 'YETI', 'YEXT', 'YGMZ', 'YI', 'YJ', 'YMAB', 'YMTX', 'YNDX', 'YORW',
    'YPF', 'YQ', 'YRCW', 'YRD', 'YSAC', 'YSACU', 'YSACW', 'YSG', 'YTEN',
    'YTRA', 'YUM', 'YUMC', 'YVR', 'YY', 'Z', 'ZAGG', 'ZBH', 'ZBRA', 'ZCMD',
    'ZDGE', 'ZEAL', 'ZEN', 'ZEUS', 'ZG', 'ZGNX', 'ZGYH', 'ZGYHR', 'ZGYHU',
    'ZGYHW', 'ZI', 'ZION', 'ZIONL', 'ZIONN', 'ZIONO', 'ZIONP', 'ZIOP', 'ZIXI',
    'ZKIN', 'ZLAB', 'ZM', 'ZNGA', 'ZNH', 'ZNTEU', 'ZNTL', 'ZOM', 'ZS', 'ZSAN',
    'ZTO', 'ZTR', 'ZTS', 'ZUMZ', 'ZUO', 'ZVO', 'ZYME', 'ZYNE', 'ZYXI'
], default=["AAPL", "NVDA", "TGT"])]

st.sidebar.title("How much money would you like to invest?")
money =  st.sidebar.number_input('Input amount in $', min_value=1, max_value=10000000, value=500)
size = len(pd.Series(assets, name='Optimal Buy')[0])
num =1 
weights = np.array([num / size for x in range (size)])

#Get the stock starting date
stockStartDate = '2019-01-1'
# Get the stocks ending date aka todays date and format it in the form YYYY-MM-DD
today = datetime.today().strftime('%Y-%m-%d')

#Create a dataframe to store the adjusted close price of the stocks
df = pd.DataFrame()
#Store the adjusted close price of stock into the data frame
for stock in assets:
        df[stock] = web.DataReader(stock,data_source='yahoo',start='2018-01-01' , end=today)['Adj Close']

# Create the title 'Portfolio Adj Close Price History
title = 'Portfolio Price History    '

#Get the stocks
my_stocks = df

#Create and plot the graph
fig = plt.figure(figsize=(12.2,4.5)) #width = 12.2in, height = 4.5

# Loop through each stock and plot the Adj Close for each day
for c in my_stocks.columns.values:
  plt.plot( my_stocks[c],  label=c)#plt.plot( X-Axis , Y-Axis, line_width, alpha_for_blending,  label)
plt.title(title)
plt.xlabel('Date',fontsize=18)
plt.ylabel('Adj. Price USD ($)',fontsize=18)
plt.legend(my_stocks.columns.values, loc='upper left')
st.pyplot(fig)
with st.beta_expander("See explanation"):
    st.write(""" The chart above shows your portfolio's past returns but does not *guarantee* future returns. """)

#Fancy Quant Math
returns = df.pct_change()
cov_matrix_annual = returns.cov() * 252
port_variance = np.dot(weights.T, np.dot(cov_matrix_annual, weights))
port_volatility = np.sqrt(port_variance)
portfolioSimpleAnnualReturn = np.sum(returns.mean()*weights) * 252

percent_var = str(round(port_variance, 2) * 100) + '%'
percent_vols = str(round(port_volatility, 2) * 100) + '%'
percent_ret = str(round(portfolioSimpleAnnualReturn, 2)*100)+'%'

#Create two columns
col1, col2, = st.beta_columns(2)

# Getting Returns 
with col1:
    st.subheader("Your Portfolio's Expected Returns")
    st.subheader("Expected annual return:") 
    st.write(percent_ret)
    st.subheader('Annual volatility/standard deviation/risk : ')
    st.write(percent_vols)
    st.subheader('Annual variance : ')
    st.write(percent_var)

mu = expected_returns.mean_historical_return(df, compounding=True) #returns.mean() * 252
S = risk_models.sample_cov(df) #Get the sample covariance matrix

ef = EfficientFrontier(mu, S)
weights =  ef.nonconvex_objective(
        objective_functions.sharpe_ratio,
        objective_args=(ef.expected_returns, ef.cov_matrix),
        weights_sum_to_one=True,
    ) #Maximize the Sharpe ratio, and get the raw weights
cleaned_weights = ef.clean_weights() 
ef.portfolio_performance(verbose=True)

with col2: 
    st.subheader("Your Portfolio's Optimal Weights")
    st.write(pd.Series(cleaned_weights, name='Optimal Weights')) #Note the weights may have some rounding error, meaning they may not add up exactly to 1 but should be close
    with st.beta_expander("See explanation"):
        st.write(""" Note the weights may have some rounding error, meaning they may not add up exactly to 1 but should be close""")

from pypfopt.discrete_allocation import DiscreteAllocation, get_latest_prices
latest_prices = get_latest_prices(df)
weights = cleaned_weights 
da = DiscreteAllocation(weights, latest_prices, total_portfolio_value=money)
allocation, leftover = da.lp_portfolio()

st.subheader("How much of each stock to buy:") 
st.write(pd.Series(allocation, name='Optimal Buy'))
   
st.subheader("Funds Remaining:") 
st.write("$"+str(round(leftover))+ " dollars left over")
